import type { StoreVertical } from "@/lib/store-profile";
import type { SizeGuide } from "./size-guide";

export type SizeGuideTemplate = {
  key: string;
  name_ar: string;
  name_en: string;
  vertical_hint: StoreVertical[];
  guide: Omit<SizeGuide, "id" | "brand_id">;
};

export const SIZE_GUIDE_TEMPLATES: SizeGuideTemplate[] = [
  {
    key: "abaya_gulf",
    name_ar: "دليل مقاسات العبايات الخليجية",
    name_en: "Gulf Abaya Size Guide",
    vertical_hint: ["fashion"],
    guide: {
      name_ar: "دليل مقاسات العبايات",
      name_en: "Abaya Size Guide",
      template_key: "abaya_gulf",
      base_unit: "in",
      columns: [
        {
          key: "length",
          label_ar: "الطول",
          label_en: "Length",
          kind: "measurement",
          measurement_key: "length",
        },
        {
          key: "bust",
          label_ar: "محيط الصدر",
          label_en: "Bust",
          kind: "measurement",
          measurement_key: "bust",
        },
        {
          key: "sleeve",
          label_ar: "طول الكم",
          label_en: "Sleeve",
          kind: "measurement",
          measurement_key: "sleeve",
        },
        {
          key: "shoulder",
          label_ar: "عرض الكتف",
          label_en: "Shoulder",
          kind: "measurement",
          measurement_key: "shoulder",
        },
      ],
      rows: [
        { label: "50", values: { length: 50, bust: 20, sleeve: 25, shoulder: 14.5 } },
        { label: "52", values: { length: 52, bust: 21, sleeve: 26, shoulder: 15 } },
        { label: "54", values: { length: 54, bust: 22, sleeve: 27, shoulder: 15.5 } },
        { label: "56", values: { length: 56, bust: 23, sleeve: 28, shoulder: 16 } },
        { label: "58", values: { length: 58, bust: 24, sleeve: 29, shoulder: 16.5 } },
        { label: "60", values: { length: 60, bust: 25, sleeve: 30, shoulder: 17 } },
      ],
      how_to_measure: [
        {
          title_ar: "الطول",
          title_en: "Length",
          body_ar: "يُقاس من أعلى الكتف عند الرقبة نزولاً حتى الطول المطلوب.",
          body_en: "Measure from the top of the shoulder down to your desired length.",
        },
        {
          title_ar: "محيط الصدر",
          title_en: "Bust",
          body_ar: "يُقاس من أوسع نقطة مع إبقاء الشريط مريحاً.",
          body_en: "Measure around the fullest part keeping the tape comfortably loose.",
        },
        {
          title_ar: "طول الكم",
          title_en: "Sleeve",
          body_ar: "يُقاس من عظمة الكتف حتى المعصم.",
          body_en: "Measure from the shoulder bone down to the wrist.",
        },
      ],
      diagram_url: null,
      video_url: null,
      notes_ar: "القياسات بالإنش. يُرجى القياس بشريط مرن مع ارتداء حذاء بالكعب المعتاد.",
      notes_en: "Measurements are in inches. Use a flexible tape wearing your regular shoes.",
      placement: "modal",
      recommender_enabled: true,
      is_default: true,
      is_active: true,
      sort_order: 0,
    },
  },
  {
    key: "women_clothing",
    name_ar: "ملابس نسائية قياسية (XS–2XL)",
    name_en: "Women's Standard Apparel (XS–2XL)",
    vertical_hint: ["fashion"],
    guide: {
      name_ar: "دليل المقاسات النسائية",
      name_en: "Women's Apparel Guide",
      template_key: "women_clothing",
      base_unit: "cm",
      columns: [
        {
          key: "bust",
          label_ar: "الصدر",
          label_en: "Bust",
          kind: "measurement",
          measurement_key: "bust",
        },
        {
          key: "waist",
          label_ar: "الخصر",
          label_en: "Waist",
          kind: "measurement",
          measurement_key: "waist",
        },
        {
          key: "hips",
          label_ar: "الأرداف",
          label_en: "Hips",
          kind: "measurement",
          measurement_key: "hips",
        },
        { key: "eu", label_ar: "الأوروبي", label_en: "EU", kind: "text" },
        { key: "uk", label_ar: "البريطاني", label_en: "UK", kind: "text" },
      ],
      rows: [
        {
          label: "XS",
          values: {
            bust: { min: 80, max: 84 },
            waist: { min: 62, max: 66 },
            hips: { min: 86, max: 90 },
            eu: "34",
            uk: "6",
          },
        },
        {
          label: "S",
          values: {
            bust: { min: 84, max: 88 },
            waist: { min: 66, max: 70 },
            hips: { min: 90, max: 94 },
            eu: "36",
            uk: "8",
          },
        },
        {
          label: "M",
          values: {
            bust: { min: 88, max: 94 },
            waist: { min: 70, max: 76 },
            hips: { min: 94, max: 100 },
            eu: "38–40",
            uk: "10–12",
          },
        },
        {
          label: "L",
          values: {
            bust: { min: 94, max: 102 },
            waist: { min: 76, max: 84 },
            hips: { min: 100, max: 108 },
            eu: "42–44",
            uk: "14–16",
          },
        },
        {
          label: "XL",
          values: {
            bust: { min: 102, max: 110 },
            waist: { min: 84, max: 92 },
            hips: { min: 108, max: 116 },
            eu: "46",
            uk: "18",
          },
        },
        {
          label: "2XL",
          values: {
            bust: { min: 110, max: 118 },
            waist: { min: 92, max: 100 },
            hips: { min: 116, max: 124 },
            eu: "48",
            uk: "20",
          },
        },
      ],
      how_to_measure: [
        {
          title_ar: "الصدر",
          title_en: "Bust",
          body_ar: "يُقاس أفقياً حول أوسع منطقة في الصدر.",
          body_en: "Measure horizontally across the fullest part of the bust.",
        },
        {
          title_ar: "الخصر",
          title_en: "Waist",
          body_ar: "يُقاس حول أضيق جزء طبيعي من الخصر فوق السرة.",
          body_en: "Measure around the narrowest part of your natural waistline.",
        },
        {
          title_ar: "الأرداف",
          title_en: "Hips",
          body_ar: "يُقاس حول أبرز نقطة من الأرداف مع ضم القدمين.",
          body_en: "Measure around the fullest part of your hips with feet together.",
        },
      ],
      diagram_url: null,
      video_url: null,
      notes_ar: "القياسات بالسنتيمتر. إذا كنتِ بين مقاسين ننصح باختيار الأكبر.",
      notes_en: "Measurements are in centimeters. If between two sizes, we recommend sizing up.",
      placement: "modal",
      recommender_enabled: true,
      is_default: false,
      is_active: true,
      sort_order: 1,
    },
  },
  {
    key: "dress",
    name_ar: "فساتين وسهرات",
    name_en: "Dresses & Evening Gowns",
    vertical_hint: ["fashion"],
    guide: {
      name_ar: "دليل مقاسات الفساتين",
      name_en: "Dress Size Guide",
      template_key: "dress",
      base_unit: "cm",
      columns: [
        {
          key: "bust",
          label_ar: "الصدر",
          label_en: "Bust",
          kind: "measurement",
          measurement_key: "bust",
        },
        {
          key: "waist",
          label_ar: "الخصر",
          label_en: "Waist",
          kind: "measurement",
          measurement_key: "waist",
        },
        {
          key: "hips",
          label_ar: "الأرداف",
          label_en: "Hips",
          kind: "measurement",
          measurement_key: "hips",
        },
        {
          key: "length",
          label_ar: "طول الفستان",
          label_en: "Length",
          kind: "measurement",
          measurement_key: "length",
        },
      ],
      rows: [
        { label: "36 / S", values: { bust: 84, waist: 66, hips: 92, length: 140 } },
        { label: "38 / M", values: { bust: 88, waist: 70, hips: 96, length: 142 } },
        { label: "40 / L", values: { bust: 92, waist: 74, hips: 100, length: 144 } },
        { label: "42 / XL", values: { bust: 98, waist: 80, hips: 106, length: 146 } },
      ],
      how_to_measure: [
        {
          title_ar: "طول الفستان",
          title_en: "Dress Length",
          body_ar: "يُقاس من منتصف الكتف نزولاً للحافة السفلية للثوب.",
          body_en: "Measure from the shoulder midpoint straight down to the hemline.",
        },
      ],
      diagram_url: null,
      video_url: null,
      notes_ar: "للفساتين الطويلة، يُراعى ارتفاع كعب الحذاء.",
      notes_en: "For floor-length gowns, consider your preferred heel height.",
      placement: "modal",
      recommender_enabled: true,
      is_default: false,
      is_active: true,
      sort_order: 2,
    },
  },
  {
    key: "men_clothing",
    name_ar: "ملابس رجالية (قمصان وبدل)",
    name_en: "Men's Apparel (Shirts & Suits)",
    vertical_hint: ["fashion"],
    guide: {
      name_ar: "دليل المقاسات الرجالية",
      name_en: "Men's Apparel Guide",
      template_key: "men_clothing",
      base_unit: "cm",
      columns: [
        {
          key: "chest",
          label_ar: "محيط الصدر",
          label_en: "Chest",
          kind: "measurement",
          measurement_key: "bust",
        },
        {
          key: "waist",
          label_ar: "محيط الخصر",
          label_en: "Waist",
          kind: "measurement",
          measurement_key: "waist",
        },
        {
          key: "shoulder",
          label_ar: "عرض الكتف",
          label_en: "Shoulder",
          kind: "measurement",
          measurement_key: "shoulder",
        },
      ],
      rows: [
        { label: "S", values: { chest: 92, waist: 78, shoulder: 44 } },
        { label: "M", values: { chest: 98, waist: 84, shoulder: 46 } },
        { label: "L", values: { chest: 104, waist: 90, shoulder: 48 } },
        { label: "XL", values: { chest: 110, waist: 96, shoulder: 50 } },
        { label: "2XL", values: { chest: 116, waist: 102, shoulder: 52 } },
      ],
      how_to_measure: [
        {
          title_ar: "محيط الصدر",
          title_en: "Chest",
          body_ar: "يُقاس حول أوسع نقطة في الصدر تحت الإبطين مباشرة.",
          body_en: "Measure around the broadest part of the chest under armpits.",
        },
      ],
      diagram_url: null,
      video_url: null,
      notes_ar: null,
      notes_en: null,
      placement: "modal",
      recommender_enabled: true,
      is_default: false,
      is_active: true,
      sort_order: 3,
    },
  },
  {
    key: "men_thobe",
    name_ar: "ثوب رجالي خليجي",
    name_en: "Men's Gulf Thobe",
    vertical_hint: ["fashion"],
    guide: {
      name_ar: "دليل مقاسات الثوب",
      name_en: "Thobe Size Guide",
      template_key: "men_thobe",
      base_unit: "in",
      columns: [
        {
          key: "length",
          label_ar: "الطول",
          label_en: "Length",
          kind: "measurement",
          measurement_key: "length",
        },
        {
          key: "chest",
          label_ar: "الصدر",
          label_en: "Chest",
          kind: "measurement",
          measurement_key: "bust",
        },
        {
          key: "sleeve",
          label_ar: "طول الكم",
          label_en: "Sleeve",
          kind: "measurement",
          measurement_key: "sleeve",
        },
      ],
      rows: [
        { label: "52", values: { length: 52, chest: 22, sleeve: 27 } },
        { label: "54", values: { length: 54, chest: 23, sleeve: 28 } },
        { label: "56", values: { length: 56, chest: 24, sleeve: 29 } },
        { label: "58", values: { length: 58, chest: 25, sleeve: 30 } },
        { label: "60", values: { length: 60, chest: 26, sleeve: 31 } },
        { label: "62", values: { length: 62, chest: 27, sleeve: 32 } },
      ],
      how_to_measure: [
        {
          title_ar: "الطول",
          title_en: "Length",
          body_ar: "يُقاس من عظمة الرقبة الخلفية حتى الكعبين.",
          body_en: "Measure from the base of the back neck straight to ankles.",
        },
      ],
      diagram_url: null,
      video_url: null,
      notes_ar: "القياسات بالإنش.",
      notes_en: "Measurements are in inches.",
      placement: "modal",
      recommender_enabled: true,
      is_default: false,
      is_active: true,
      sort_order: 4,
    },
  },
  {
    key: "shoes",
    name_ar: "أحذية وأقدام (EU / UK / US / سم)",
    name_en: "Footwear & Shoes (EU / UK / US / cm)",
    vertical_hint: ["fashion", "general"],
    guide: {
      name_ar: "دليل مقاسات الأحذية",
      name_en: "Footwear Size Guide",
      template_key: "shoes",
      base_unit: "cm",
      columns: [
        {
          key: "foot_length",
          label_ar: "طول القدم (سم)",
          label_en: "Foot Length (cm)",
          kind: "measurement",
          measurement_key: "foot_length",
        },
        { key: "eu", label_ar: "الأوروبي (EU)", label_en: "EU", kind: "text" },
        { key: "uk", label_ar: "البريطاني (UK)", label_en: "UK", kind: "text" },
        { key: "us", label_ar: "الأمريكي (US)", label_en: "US", kind: "text" },
      ],
      rows: [
        { label: "36", values: { foot_length: 23, eu: "36", uk: "3.5", us: "5" } },
        { label: "37", values: { foot_length: 23.5, eu: "37", uk: "4", us: "5.5" } },
        { label: "38", values: { foot_length: 24, eu: "38", uk: "5", us: "6.5" } },
        { label: "39", values: { foot_length: 24.5, eu: "39", uk: "6", us: "7.5" } },
        { label: "40", values: { foot_length: 25, eu: "40", uk: "6.5", us: "8" } },
        { label: "41", values: { foot_length: 25.5, eu: "41", uk: "7.5", us: "9" } },
        { label: "42", values: { foot_length: 26, eu: "42", uk: "8", us: "9.5" } },
        { label: "43", values: { foot_length: 26.5, eu: "43", uk: "9", us: "10.5" } },
      ],
      how_to_measure: [
        {
          title_ar: "طول القدم",
          title_en: "Foot Length",
          body_ar:
            "قف على ورقة بيضاء، حدّد أطول أصبع ونهاية الكعب بقلم عمودي، ثم قِس المسافة بالمسطرة.",
          body_en:
            "Stand on a piece of paper, mark your longest toe and heel end, then measure the distance.",
        },
      ],
      diagram_url: null,
      video_url: null,
      notes_ar: "قِس قدمك في نهاية اليوم عندما تكون بأقصى تمددها.",
      notes_en: "Measure your feet at the end of the day when they are at their largest.",
      placement: "modal",
      recommender_enabled: true,
      is_default: false,
      is_active: true,
      sort_order: 5,
    },
  },
  {
    key: "rings",
    name_ar: "خواتم ومجوهرات (US / قطر / محيط)",
    name_en: "Rings & Jewelry (US / Diameter / Circumference)",
    vertical_hint: ["jewelry"],
    guide: {
      name_ar: "دليل مقاسات الخواتم",
      name_en: "Ring Size Guide",
      template_key: "rings",
      base_unit: "none",
      columns: [
        { key: "us", label_ar: "المقاس الأمريكي (US)", label_en: "US Size", kind: "text" },
        {
          key: "diameter",
          label_ar: "القطر الداخلي (ملم)",
          label_en: "Inner Diameter (mm)",
          kind: "measurement",
          measurement_key: "ring_diameter",
        },
        {
          key: "circumference",
          label_ar: "محيط الإصبع (ملم)",
          label_en: "Circumference (mm)",
          kind: "measurement",
          measurement_key: "ring_circumference",
        },
      ],
      rows: [
        { label: "US 5", values: { us: "5", diameter: 15.7, circumference: 49.3 } },
        { label: "US 6", values: { us: "6", diameter: 16.5, circumference: 51.9 } },
        { label: "US 7", values: { us: "7", diameter: 17.3, circumference: 54.4 } },
        { label: "US 8", values: { us: "8", diameter: 18.1, circumference: 57.0 } },
        { label: "US 9", values: { us: "9", diameter: 18.9, circumference: 59.5 } },
      ],
      how_to_measure: [
        {
          title_ar: "محيط الإصبع",
          title_en: "Finger Circumference",
          body_ar: "لُف شريط ورقي حول المفصل، حدّد نقطة الالتقاء وقِس طوله بالمليمتر.",
          body_en: "Wrap a strip of paper around your knuckle, mark the overlap and measure in mm.",
        },
      ],
      diagram_url: null,
      video_url: null,
      notes_ar: "تأكد من قياس المفصل لضمان دخول الخاتم بسلاسة.",
      notes_en: "Make sure to measure the knuckle so the ring slides over smoothly.",
      placement: "modal",
      recommender_enabled: true,
      is_default: false,
      is_active: true,
      sort_order: 6,
    },
  },
  {
    key: "bracelets",
    name_ar: "أساور ومجوهرات",
    name_en: "Bracelets & Jewelry",
    vertical_hint: ["jewelry"],
    guide: {
      name_ar: "دليل مقاسات الأساور",
      name_en: "Bracelet Size Guide",
      template_key: "bracelets",
      base_unit: "cm",
      columns: [
        {
          key: "wrist",
          label_ar: "محيط المعصم (سم)",
          label_en: "Wrist Circumference (cm)",
          kind: "measurement",
          measurement_key: "wrist",
        },
        { key: "size", label_ar: "المقاس المناسب", label_en: "Recommended Size", kind: "text" },
      ],
      rows: [
        { label: "S", values: { wrist: 15, size: "Small (15-16 cm)" } },
        { label: "M", values: { wrist: 17, size: "Medium (17-18 cm)" } },
        { label: "L", values: { wrist: 19, size: "Large (19-20 cm)" } },
      ],
      how_to_measure: [
        {
          title_ar: "محيط المعصم",
          title_en: "Wrist Circumference",
          body_ar: "لف شريط القياس حول معصمك فوق العظمة مباشرة وأضف 1-2 سم للراحة.",
          body_en:
            "Wrap the measuring tape around your wrist just above the bone and add 1-2 cm for comfort.",
        },
      ],
      diagram_url: null,
      video_url: null,
      notes_ar: "إذا كنت تفضل السوار مريحاً وفضفاضاً، اختر مقاساً أكبر.",
      notes_en: "If you prefer a loose fit, choose one size up.",
      placement: "modal",
      recommender_enabled: true,
      is_default: false,
      is_active: true,
      sort_order: 7,
    },
  },
  {
    key: "kids",
    name_ar: "أطفال حسب العمر والارتفاع",
    name_en: "Kids by Age & Height",
    vertical_hint: ["fashion"],
    guide: {
      name_ar: "دليل مقاسات الأطفال",
      name_en: "Kids Size Guide",
      template_key: "kids",
      base_unit: "cm",
      columns: [
        { key: "age", label_ar: "العمر التقديري", label_en: "Approx Age", kind: "text" },
        {
          key: "height",
          label_ar: "طول الطفل (سم)",
          label_en: "Height (cm)",
          kind: "measurement",
          measurement_key: "height",
        },
        {
          key: "chest",
          label_ar: "محيط الصدر (سم)",
          label_en: "Chest (cm)",
          kind: "measurement",
          measurement_key: "bust",
        },
      ],
      rows: [
        { label: "2Y", values: { age: "1-2 سنة", height: 92, chest: 53 } },
        { label: "3Y", values: { age: "2-3 سنوات", height: 98, chest: 55 } },
        { label: "4Y", values: { age: "3-4 سنوات", height: 104, chest: 57 } },
        { label: "5Y", values: { age: "4-5 سنوات", height: 110, chest: 59 } },
        { label: "6Y", values: { age: "5-6 سنوات", height: 116, chest: 61 } },
        { label: "8Y", values: { age: "7-8 سنوات", height: 128, chest: 65 } },
      ],
      how_to_measure: [
        {
          title_ar: "طول الطفل",
          title_en: "Child Height",
          body_ar: "يُقاس من أعلى الرأس حتى أخمص القدمين أثناء استلقاء الرضيع أو وقوف الطفل.",
          body_en:
            "Measure from head top to heels with baby lying flat or child standing straight.",
        },
      ],
      diagram_url: null,
      video_url: null,
      notes_ar: "الأطفال ينمون سريعاً، ننصح باختيار مقاس أكبر لشهر إضافي.",
      notes_en: "Kids grow fast, we recommend choosing one size up.",
      placement: "modal",
      recommender_enabled: true,
      is_default: false,
      is_active: true,
      sort_order: 8,
    },
  },
];

export const ALL_SIZE_GUIDE_TEMPLATES = SIZE_GUIDE_TEMPLATES.map((t) => ({
  key: t.key,
  vertical_hint: t.vertical_hint,
  vertical_description_ar: t.name_ar,
  vertical_description_en: t.name_en,
  ...t.guide,
  rows: t.guide.rows.map((r) => ({
    ...r,
    size_label: r.label,
  })),
}));

export const ABAYA_GULF_TEMPLATE = ALL_SIZE_GUIDE_TEMPLATES[0];

export function getSizeGuideTemplate(key: string) {
  const found = ALL_SIZE_GUIDE_TEMPLATES.find((t) => t.key === key);
  return found ?? null;
}
