/**
 * Legacy save payload columns snapshot.
 * Extracted directly from existing handlers in `admin.b.$slug.settings.tsx`:
 * - lines 880-925 (General / Invoicing)
 * - line 2996 (Payments)
 * - lines 4420-4430 (Shipping)
 * - lines 6155-6160 (Storefront Mode)
 * - lines 6810-6830 (Storefront Customizer)
 * - lines 8952-8964 (Notifications)
 *
 * Used as a baseline verification test to ensure PR #1 and PR #2 do not lose
 * any existing column saved by legacy handlers.
 * Will be removed at the end of Phase 2 once single unified save model is fully active.
 */

export const LEGACY_GENERAL_SAVE_COLUMNS = [
  "business_name",
  "logo_url",
  "favicon_url",
  "address",
  "phone",
  "email",
  "vat_number",
  "currency",
  "default_tax_rate",
  "primary_color",
  "footer_note",
  "font_family",
  "font_url",
  "font_size",
  "text_color",
  "background_color",
  "logo_size",
  "logo_x",
  "logo_y",
  "logo_width",
  "logo_height",
  "invoice_template",
  "invoice_secondary_color",
  "invoice_show_business_details",
  "invoice_show_customer_contact",
  "invoice_show_fulfillment",
  "invoice_show_notes",
  "invoice_title_en",
  "invoice_title_ar",
  "invoice_arabic_font_family",
  "invoice_status_paid_color",
  "invoice_status_unpaid_color",
  "invoice_status_progress_color",
  "invoice_table_header_bg",
  "invoice_table_header_fg",
  "invoice_divider_color",
  "invoice_show_business_name",
  "invoice_show_terms",
  "invoice_terms_ar",
  "invoice_terms_en",
] as const;

export const LEGACY_PAYMENTS_SAVE_COLUMNS = [
  "cod_enabled",
  "card_enabled",
  "benefit_enabled",
  "benefit_qr_url",
  "benefit_account_number",
  "card_processing_fee",
  "benefit_processing_fee",
  "card_public_key",
  "card_secret_key",
] as const;

export const LEGACY_SHIPPING_SAVE_COLUMNS = [
  "delivery_enabled",
  "pickup_enabled",
  "digital_delivery_enabled",
  "delivery_fee",
  "delivery_estimate_enabled",
  "delivery_estimate_ar",
  "delivery_estimate_en",
  "shipping_zones",
  "benefit_account_number",
] as const;

export const LEGACY_MODE_SAVE_COLUMNS = [
  "storefront_mode",
  "catalog_show_prices",
  "whatsapp_number",
  "catalog_inquiry_message_ar",
  "catalog_inquiry_message_en",
] as const;

export const LEGACY_STOREFRONT_CUSTOMIZER_COLUMNS = [
  "logo_size",
  "footer_logo_size",
  "logo_align",
  "show_header_name",
  "show_hero_title",
  "show_hero_about",
  "show_footer_name",
  "storefront_font_en",
  "storefront_font_ar",
  "storefront_font_en_url",
  "storefront_font_ar_url",
  "storefront_typography",
  "admin_typography",
  "storefront_radius",
  "header_glass",
  "badge_accent",
  "secondary_banner_parallax_enabled",
  "secondary_banner_parallax_mobile_enabled",
  "secondary_banner_parallax_breakpoint",
  "trending_banner_background_url",
  "category_banner_background_url",
  "hero_title_en",
  "hero_title_ar",
  "hero_title_size",
  "hero_title_color",
  "hero_title_align",
  "storefront_accent_color",
  "storefront_background_color",
  "storefront_text_color",
  "header_bg",
  "header_fg",
  "footer_bg",
  "footer_fg",
  "heading_color",
  "link_color",
  "price_color",
  "product_title_color",
  "btn_primary_bg",
  "btn_primary_fg",
  "btn_secondary_bg",
  "btn_secondary_fg",
  "btn_checkout_bg",
  "btn_checkout_fg",
  "menu_bg",
  "menu_fg",
  "menu_title_en",
  "menu_title_ar",
  "menu_show_home",
  "menu_show_account",
  "menu_show_orders",
  "menu_show_pages",
  "home_promo_cards",
  "homepage_editorial_sections",
  "show_new_arrivals",
  "show_best_sellers",
  "new_arrivals_title_en",
  "new_arrivals_title_ar",
  "best_sellers_title_en",
  "best_sellers_title_ar",
  "announcement_enabled",
  "announcement_text_en",
  "announcement_text_ar",
  "announcement_bg",
  "announcement_fg",
  "announcement_bold",
  "announcement_italic",
  "announcement_dismissible",
  "announcement_scope",
  "announcement_audience",
  "global_sale_badges_enabled",
  "cart_drawer_checkout_bg",
  "cart_drawer_checkout_fg",
  "storefront_loader_text_en",
  "storefront_loader_text_ar",
  "trust_badges",
] as const;

export const LEGACY_NOTIFICATIONS_SAVE_COLUMNS = [
  "email_sender_name",
  "email_intro_ar",
  "email_intro_en",
  "email_footer_ar",
  "email_footer_en",
  "courier_out_for_delivery_message_ar",
  "courier_out_for_delivery_message_en",
] as const;

export const ALL_LEGACY_SAVE_COLUMNS: readonly string[] = Array.from(
  new Set([
    ...LEGACY_GENERAL_SAVE_COLUMNS,
    ...LEGACY_PAYMENTS_SAVE_COLUMNS,
    ...LEGACY_SHIPPING_SAVE_COLUMNS,
    ...LEGACY_MODE_SAVE_COLUMNS,
    ...LEGACY_STOREFRONT_CUSTOMIZER_COLUMNS,
    ...LEGACY_NOTIFICATIONS_SAVE_COLUMNS,
  ]),
);
