export type SettingsTabId = "identity" | "storefront" | "orders" | "notifications" | "account";
export type SettingsLevel = "basic" | "advanced";
export type SettingsOwner =
  | "settings" // يُعدَّل داخل صفحة الإعدادات
  | "route:pages" // يُعدَّل في صفحة الصفحات والسياسات
  | "route:integrations"
  | "route:team"
  | "route:expenses" // bom_enabled يُدار من صفحة المصروفات
  | "system"; // لا يُعدَّل يدوياً (created_at, user_id, next_invoice_number...)

export interface SettingsFieldDef {
  key: string; // اسم العمود
  table: "business_settings" | "brands";
  tab: SettingsTabId | null; // null عندما owner !== "settings"
  group: string | null; // معرّف المجموعة داخل التبويب
  level: SettingsLevel;
  owner: SettingsOwner;
  type: "text" | "textarea" | "number" | "boolean" | "color" | "select" | "image" | "font" | "json";
  label: { ar: string; en: string };
  keywords?: { ar: string[]; en: string[] };
  readOnlyMirrors?: string[]; // أماكن تعرض القيمة للقراءة فقط (توثيق)
  selfSaving?: boolean; // حقول لها تدفق حفظ خاص ومستقل مثل StoreProfileCard
}

export interface SettingsTabDef {
  id: SettingsTabId;
  label: { ar: string; en: string };
  description: { ar: string; en: string };
}

export const SETTINGS_TABS: SettingsTabDef[] = [
  {
    id: "identity",
    label: { ar: "الهوية والعلامة", en: "Identity" },
    description: { ar: "الشعار والألوان والخطوط", en: "Logos, colors & fonts" },
  },
  {
    id: "storefront",
    label: { ar: "المتجر والرئيسية", en: "Storefront" },
    description: { ar: "الواجهة والبنرات والسيو", en: "Homepage, banners & SEO" },
  },
  {
    id: "orders",
    label: { ar: "الطلبات والمدفوعات", en: "Orders & Checkout" },
    description: { ar: "طرق الدفع والشحن والفواتير", en: "Payments, shipping & invoice" },
  },
  {
    id: "notifications",
    label: { ar: "الإشعارات", en: "Notifications" },
    description: { ar: "قوالب وتنبيهات الطلبات", en: "Email templates & recipients" },
  },
  {
    id: "account",
    label: { ar: "الحساب والأمان", en: "Account" },
    description: { ar: "المستخدم والوصول ووضع الصيانة", en: "User, access & maintenance" },
  },
];

export const SETTINGS_GROUPS: Record<SettingsTabId, { id: string; ar: string; en: string }[]> = {
  identity: [
    { id: "basics", ar: "الاسم والشعار", en: "Name & Logo" },
    { id: "vertical", ar: "نوع النشاط والوحدات", en: "Store Vertical & Modules" },
    { id: "palette", ar: "الألوان", en: "Colours" },
    { id: "typography", ar: "الخطوط", en: "Typography" },
    { id: "contact", ar: "التواصل والعنوان", en: "Contact & Address" },
  ],
  storefront: [
    { id: "mode", ar: "وضع البيع", en: "Selling Mode" },
    { id: "home_hero", ar: "الواجهة الرئيسية (Hero)", en: "Homepage Hero" },
    { id: "home_sections", ar: "أقسام الصفحة الرئيسية", en: "Homepage Sections" },
    { id: "header_footer", ar: "الترويسة والقائمة والتذييل", en: "Header, Menu & Footer" },
    { id: "announcement", ar: "شريط الإعلانات", en: "Announcement Bar" },
    { id: "loader", ar: "شاشة التحميل", en: "Loading Screen" },
    { id: "seo", ar: "محركات البحث (SEO)", en: "SEO" },
  ],
  orders: [
    { id: "payments", ar: "طرق الدفع", en: "Payment Methods" },
    { id: "pricing", ar: "العملة والضريبة", en: "Currency & Tax" },
    { id: "fulfillment", ar: "التوصيل والاستلام", en: "Delivery & Pickup" },
    { id: "invoice", ar: "الفاتورة", en: "Invoice" },
  ],
  notifications: [
    { id: "templates", ar: "نصوص الرسائل", en: "Message Templates" },
    { id: "recipients", ar: "مستلمو الإشعارات", en: "Notification Recipients" },
  ],
  account: [
    { id: "subscription", ar: "الاشتراك", en: "Subscription" },
    { id: "security", ar: "الأمان", en: "Security" },
    { id: "apps", ar: "تطبيقات الجوال", en: "Mobile Apps" },
  ],
};

export const SETTINGS_REGISTRY: SettingsFieldDef[] = [
  // ==========================================
  // IDENTITY TAB
  // ==========================================

  // identity.basics
  {
    key: "business_name",
    table: "business_settings",
    tab: "identity",
    group: "basics",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "اسم المتجر", en: "Store Name" },
    keywords: { ar: ["اسم", "متجر", "علامة"], en: ["name", "business", "store"] },
  },
  {
    key: "logo_url",
    table: "business_settings",
    tab: "identity",
    group: "basics",
    level: "basic",
    owner: "settings",
    type: "image",
    label: { ar: "شعار المتجر", en: "Store Logo" },
    keywords: { ar: ["شعار", "لوجو", "صورة"], en: ["logo", "brand mark", "icon"] },
  },
  {
    key: "favicon_url",
    table: "business_settings",
    tab: "identity",
    group: "basics",
    level: "basic",
    owner: "settings",
    type: "image",
    label: { ar: "أيقونة التبويب (Favicon)", en: "Favicon" },
    keywords: { ar: ["أيقونة", "تبويب", "فافيكون"], en: ["favicon", "browser icon"] },
  },

  // identity.vertical
  {
    key: "store_vertical",
    table: "business_settings",
    tab: "identity",
    group: "vertical",
    level: "basic",
    owner: "settings",
    type: "select",
    selfSaving: true,
    label: { ar: "نوع النشاط التجاري", en: "Store Vertical" },
    keywords: { ar: ["نشاط", "نوع", "عبايات", "أزياء", "عطور", "مطعم"], en: ["vertical", "industry", "business type"] },
  },
  {
    key: "store_modules",
    table: "business_settings",
    tab: "identity",
    group: "vertical",
    level: "advanced",
    owner: "settings",
    type: "json",
    selfSaving: true,
    label: { ar: "وحدات وموديولات المتجر", en: "Store Modules" },
    keywords: { ar: ["وحدات", "موديول", "ميزات"], en: ["modules", "features", "capabilities"] },
  },
  {
    key: "fit_profiles",
    table: "business_settings",
    tab: "identity",
    group: "vertical",
    level: "advanced",
    owner: "settings",
    type: "json",
    selfSaving: true,
    label: { ar: "ملفات القياس والتفصيل", en: "Fit Profiles" },
    keywords: { ar: ["قياس", "تفصيل", "مقاسات"], en: ["fit", "sizing", "measurements"] },
  },

  // identity.palette
  {
    key: "storefront_accent_color",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "basic",
    owner: "settings",
    type: "color",
    label: { ar: "لون العلامة الأساسي (Accent Color)", en: "Primary Accent Color" },
    keywords: { ar: ["لون", "رئيسي", "أساسي", "هوية"], en: ["accent", "primary color", "theme"] },
  },
  {
    key: "storefront_background_color",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون خلفية المتجر", en: "Storefront Background Color" },
    keywords: { ar: ["خلفية", "لون الخلفية"], en: ["background color", "canvas"] },
  },
  {
    key: "storefront_text_color",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون النصوص العامة", en: "Storefront Text Color" },
    keywords: { ar: ["نصوص", "كتابة", "لون النص"], en: ["text color", "body color"] },
  },
  {
    key: "brand_palette",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "json",
    label: { ar: "لوحة الألوان المستخرجة للهوية", en: "Brand Palette (Extracted JSON)" },
    keywords: { ar: ["لوحة ألوان", "باليت", "ألوان مستخرجة"], en: ["palette", "colors", "brand palette"] },
  },
  {
    key: "heading_color",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون العناوين", en: "Heading Color" },
    keywords: { ar: ["عناوين", "عنوان"], en: ["heading color", "titles"] },
  },
  {
    key: "link_color",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون الروابط", en: "Link Color" },
    keywords: { ar: ["روابط", "رابط"], en: ["link color", "hyperlink"] },
  },
  {
    key: "price_color",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون عرض السعر", en: "Price Color" },
    keywords: { ar: ["سعر", "أسعار"], en: ["price color", "amount"] },
  },
  {
    key: "product_title_color",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون اسم المنتج", en: "Product Title Color" },
    keywords: { ar: ["منتج", "اسم المنتج"], en: ["product title", "product name"] },
  },
  {
    key: "btn_primary_bg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "خلفية الزر الأساسي", en: "Primary Button Background" },
    keywords: { ar: ["زر", "أزرار", "زر أساسي"], en: ["primary button bg"] },
  },
  {
    key: "btn_primary_fg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "نص الزر الأساسي", en: "Primary Button Text" },
    keywords: { ar: ["نص الزر الأساسي"], en: ["primary button text"] },
  },
  {
    key: "btn_secondary_bg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "خلفية الزر الثانوي", en: "Secondary Button Background" },
    keywords: { ar: ["زر ثانوي"], en: ["secondary button bg"] },
  },
  {
    key: "btn_secondary_fg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "نص الزر الثانوي", en: "Secondary Button Text" },
    keywords: { ar: ["نص الزر الثانوي"], en: ["secondary button text"] },
  },
  {
    key: "btn_checkout_bg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "خلفية زر إتمام الطلب", en: "Checkout Button Background" },
    keywords: { ar: ["زر الدفع", "إتمام الطلب"], en: ["checkout button bg"] },
  },
  {
    key: "btn_checkout_fg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "نص زر إتمام الطلب", en: "Checkout Button Text" },
    keywords: { ar: ["نص زر الدفع"], en: ["checkout button text"] },
  },
  {
    key: "cart_drawer_checkout_bg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "خلفية زر سلة المشتريات الجانبية", en: "Cart Drawer Checkout Background" },
    keywords: { ar: ["سلة", "درج السلة"], en: ["cart drawer checkout bg"] },
  },
  {
    key: "cart_drawer_checkout_fg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "نص زر سلة المشتريات الجانبية", en: "Cart Drawer Checkout Text" },
    keywords: { ar: ["نص زر سلة المشتريات"], en: ["cart drawer checkout text"] },
  },
  {
    key: "header_bg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "خلفية الترويسة (Header)", en: "Header Background" },
    keywords: { ar: ["ترويسة", "هيدر"], en: ["header bg"] },
  },
  {
    key: "header_fg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "نص وأيقونات الترويسة", en: "Header Foreground" },
    keywords: { ar: ["نص الترويسة", "أيقونات الترويسة"], en: ["header fg"] },
  },
  {
    key: "footer_bg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "خلفية التذييل (Footer)", en: "Footer Background" },
    keywords: { ar: ["تذييل", "فوتر"], en: ["footer bg"] },
  },
  {
    key: "footer_fg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "نص وروابط التذييل", en: "Footer Foreground" },
    keywords: { ar: ["نص التذييل", "فوتر"], en: ["footer fg"] },
  },
  {
    key: "menu_bg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "خلفية القائمة المتنقلة", en: "Mobile Menu Background" },
    keywords: { ar: ["قائمة", "منيو"], en: ["menu bg"] },
  },
  {
    key: "menu_fg",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "نص القائمة المتنقلة", en: "Mobile Menu Foreground" },
    keywords: { ar: ["نص القائمة"], en: ["menu fg"] },
  },
  {
    key: "badge_accent",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "select",
    label: { ar: "لون الشارات والخصومات", en: "Badge Accent Tone" },
    keywords: { ar: ["شارة", "خصم", "بادج"], en: ["badge", "sale badge", "accent tone"] },
  },
  {
    key: "storefront_radius",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "select",
    label: { ar: "استدارة الحواف والبطاقات", en: "Storefront Corner Radius" },
    keywords: { ar: ["زوايا", "انحناء", "حواف"], en: ["radius", "corners", "curves"] },
  },
  {
    key: "header_glass",
    table: "business_settings",
    tab: "identity",
    group: "palette",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "تأثير زجاجي للترويسة (Glassmorphism)", en: "Header Glassmorphism" },
    keywords: { ar: ["زجاج", "تأثير زجاجي", "شفافية"], en: ["glass", "blur", "backdrop"] },
  },
  {
    key: "primary_color",
    table: "brands",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "color",
    label: { ar: "لون العلامة الأساسي للبراند (مشتق)", en: "Brand Primary Color (Derived)" },
    keywords: { ar: ["لون", "أساسي"], en: ["brand primary color"] },
  },

  // identity.typography
  {
    key: "storefront_font_en",
    table: "business_settings",
    tab: "identity",
    group: "typography",
    level: "basic",
    owner: "settings",
    type: "font",
    label: { ar: "الخط الإنجليزي للمتجر", en: "English Storefront Font" },
    keywords: { ar: ["خط إنجليزي", "خط"], en: ["english font", "typography"] },
  },
  {
    key: "storefront_font_ar",
    table: "business_settings",
    tab: "identity",
    group: "typography",
    level: "basic",
    owner: "settings",
    type: "font",
    label: { ar: "الخط العربي للمتجر", en: "Arabic Storefront Font" },
    keywords: { ar: ["خط عربي", "خط"], en: ["arabic font", "typography"] },
  },
  {
    key: "storefront_font_en_url",
    table: "business_settings",
    tab: "identity",
    group: "typography",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "رابط الخط الإنجليزي المخصص", en: "Custom English Font URL" },
    keywords: { ar: ["رابط خط", "خط مخصص"], en: ["custom font url"] },
  },
  {
    key: "storefront_font_ar_url",
    table: "business_settings",
    tab: "identity",
    group: "typography",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "رابط الخط العربي المخصص", en: "Custom Arabic Font URL" },
    keywords: { ar: ["رابط خط عربي", "خط مخصص"], en: ["custom font url"] },
  },
  {
    key: "storefront_typography",
    table: "business_settings",
    tab: "identity",
    group: "typography",
    level: "advanced",
    owner: "settings",
    type: "json",
    label: { ar: "إعدادات تايبوغرافي المتجر المتقدمة", en: "Storefront Typography Preset" },
    keywords: { ar: ["خطوط متقدمة", "تايبوغرافي"], en: ["typography preset", "display body"] },
  },
  {
    key: "admin_typography",
    table: "business_settings",
    tab: "identity",
    group: "typography",
    level: "advanced",
    owner: "settings",
    type: "json",
    label: { ar: "خطوط لوحة التحكم", en: "Admin Dashboard Typography" },
    keywords: { ar: ["خط لوحة التحكم"], en: ["admin font"] },
  },

  // identity.contact
  {
    key: "address",
    table: "business_settings",
    tab: "identity",
    group: "contact",
    level: "basic",
    owner: "settings",
    type: "textarea",
    label: { ar: "العنوان ومقر العمل", en: "Store Physical Address" },
    keywords: { ar: ["عنوان", "مقر", "موقع"], en: ["address", "location"] },
  },
  {
    key: "phone",
    table: "business_settings",
    tab: "identity",
    group: "contact",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "رقم الهاتف الرسمي", en: "Store Contact Phone" },
    keywords: { ar: ["هاتف", "تلفون", "اتصال"], en: ["phone", "telephone", "contact"] },
  },
  {
    key: "email",
    table: "business_settings",
    tab: "identity",
    group: "contact",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "البريد الإلكتروني الرسمي", en: "Store Contact Email" },
    keywords: { ar: ["بريد", "إيميل"], en: ["email", "contact email"] },
  },
  {
    key: "whatsapp_number",
    table: "business_settings",
    tab: "identity",
    group: "contact",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "رقم الواتساب للتواصل", en: "WhatsApp Contact Number" },
    keywords: { ar: ["واتساب", "رقم واتساب"], en: ["whatsapp", "whatsapp number"] },
  },
  {
    key: "socials",
    table: "business_settings",
    tab: null,
    group: null,
    level: "advanced",
    owner: "route:pages",
    type: "json",
    label: { ar: "حسابات التواصل الاجتماعي", en: "Social Media Links" },
    keywords: { ar: ["تواصل", "انستغرام", "سوشيال"], en: ["socials", "instagram", "tiktok"] },
    readOnlyMirrors: ["admin.b.$slug.pages.tsx"],
  },
  {
    key: "custom_domain",
    table: "brands",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "text",
    label: { ar: "الدومين المخصص", en: "Custom Domain" },
    keywords: { ar: ["دومين", "نطاق"], en: ["domain", "custom domain"] },
  },

  // ==========================================
  // STOREFRONT TAB
  // ==========================================

  // storefront.mode
  {
    key: "storefront_mode",
    table: "business_settings",
    tab: "storefront",
    group: "mode",
    level: "basic",
    owner: "settings",
    type: "select",
    label: { ar: "وضع المتجر (شراء مباشر أو كتالوج)", en: "Storefront Mode (Shop or Catalog)" },
    keywords: { ar: ["وضع المتجر", "شراء مباشر", "كتالوج", "استفسار"], en: ["mode", "shop", "catalog"] },
  },
  {
    key: "catalog_show_prices",
    table: "business_settings",
    tab: "storefront",
    group: "mode",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "إظهار الأسعار في وضع الكتالوج", en: "Show Prices in Catalog Mode" },
    keywords: { ar: ["إظهار الأسعار", "كتالوج"], en: ["catalog prices", "show price"] },
  },
  {
    key: "catalog_inquiry_message_ar",
    table: "business_settings",
    tab: "storefront",
    group: "mode",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "رسالة الاستفسار عبر واتساب (عربي)", en: "WhatsApp Inquiry Message (Arabic)" },
    keywords: { ar: ["رسالة استفسار", "واتساب كتالوج"], en: ["inquiry template arabic"] },
  },
  {
    key: "catalog_inquiry_message_en",
    table: "business_settings",
    tab: "storefront",
    group: "mode",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "رسالة الاستفسار عبر واتساب (إنجليزي)", en: "WhatsApp Inquiry Message (English)" },
    keywords: { ar: ["رسالة استفسار إنجليزي"], en: ["inquiry template english"] },
  },
  {
    key: "whatsapp_enabled",
    table: "business_settings",
    tab: "storefront",
    group: "mode",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "تفعيل زر الواتساب العائم في المتجر", en: "Enable Floating WhatsApp Button" },
    keywords: { ar: ["زر واتساب", "عائم"], en: ["floating whatsapp", "whatsapp widget"] },
  },

  // storefront.home_hero
  {
    key: "hero_media",
    table: "brands",
    tab: "storefront",
    group: "home_hero",
    level: "basic",
    owner: "settings",
    type: "json",
    label: { ar: "وسائط الواجهة الرئيسية (صور وفيديو Hero)", en: "Homepage Hero Media" },
    keywords: { ar: ["هيرو", "فيديو", "صور رئيسية"], en: ["hero media", "hero banner"] },
  },
  {
    key: "about_ar",
    table: "brands",
    tab: "storefront",
    group: "home_hero",
    level: "basic",
    owner: "settings",
    type: "textarea",
    label: { ar: "نبذة عن المتجر في الواجهة (عربي)", en: "About Story (Arabic)" },
    keywords: { ar: ["قصة", "نبذة", "عن المتجر"], en: ["about brand", "story arabic"] },
  },
  {
    key: "about_en",
    table: "brands",
    tab: "storefront",
    group: "home_hero",
    level: "basic",
    owner: "settings",
    type: "textarea",
    label: { ar: "نبذة عن المتجر في الواجهة (إنجليزي)", en: "About Story (English)" },
    keywords: { ar: ["نبذة إنجليزي"], en: ["about brand english"] },
  },
  {
    key: "show_hero_title",
    table: "business_settings",
    tab: "storefront",
    group: "home_hero",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض عنوان الواجهة الترحيبي", en: "Show Hero Title" },
    keywords: { ar: ["عرض العنوان", "هيرو"], en: ["show hero title"] },
  },
  {
    key: "show_hero_about",
    table: "business_settings",
    tab: "storefront",
    group: "home_hero",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض نبذة المتجر في الواجهة", en: "Show About Section in Hero" },
    keywords: { ar: ["عرض النبذة"], en: ["show hero about"] },
  },
  {
    key: "hero_title_en",
    table: "business_settings",
    tab: "storefront",
    group: "home_hero",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "عنوان الواجهة الترحيبي (إنجليزي)", en: "Hero Title (English)" },
    keywords: { ar: ["عنوان ترحيبي إنجليزي"], en: ["hero title en"] },
  },
  {
    key: "hero_title_ar",
    table: "business_settings",
    tab: "storefront",
    group: "home_hero",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "عنوان الواجهة الترحيبي (عربي)", en: "Hero Title (Arabic)" },
    keywords: { ar: ["عنوان ترحيبي عربي"], en: ["hero title ar"] },
  },
  {
    key: "hero_title_size",
    table: "business_settings",
    tab: "storefront",
    group: "home_hero",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "حجم خط عنوان الواجهة (px)", en: "Hero Title Size (px)" },
    keywords: { ar: ["حجم خط العنوان"], en: ["hero title font size"] },
  },
  {
    key: "hero_title_color",
    table: "business_settings",
    tab: "storefront",
    group: "home_hero",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون عنوان الواجهة", en: "Hero Title Color" },
    keywords: { ar: ["لون عنوان الواجهة"], en: ["hero title color"] },
  },
  {
    key: "hero_title_align",
    table: "business_settings",
    tab: "storefront",
    group: "home_hero",
    level: "advanced",
    owner: "settings",
    type: "select",
    label: { ar: "محاذاة عنوان الواجهة", en: "Hero Title Alignment" },
    keywords: { ar: ["محاذاة العنوان", "يمين", "وسط", "يسار"], en: ["hero title align", "center", "start"] },
  },

  // storefront.home_sections
  {
    key: "show_new_arrivals",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض قسم وصل حديثاً", en: "Show New Arrivals Section" },
    keywords: { ar: ["وصل حديثاً", "جديد"], en: ["new arrivals"] },
  },
  {
    key: "show_best_sellers",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض قسم الأكثر مبيعاً", en: "Show Best Sellers Section" },
    keywords: { ar: ["الأكثر مبيعاً", "أفضل المبيعات"], en: ["best sellers"] },
  },
  {
    key: "new_arrivals_title_ar",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "عنوان قسم وصل حديثاً (عربي)", en: "New Arrivals Title (Arabic)" },
    keywords: { ar: ["عنوان وصل حديثاً"], en: ["new arrivals title ar"] },
  },
  {
    key: "new_arrivals_title_en",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "عنوان قسم وصل حديثاً (إنجليزي)", en: "New Arrivals Title (English)" },
    keywords: { ar: ["عنوان وصل حديثاً إنجليزي"], en: ["new arrivals title en"] },
  },
  {
    key: "best_sellers_title_ar",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "عنوان قسم الأكثر مبيعاً (عربي)", en: "Best Sellers Title (Arabic)" },
    keywords: { ar: ["عنوان الأكثر مبيعاً"], en: ["best sellers title ar"] },
  },
  {
    key: "best_sellers_title_en",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "عنوان قسم الأكثر مبيعاً (إنجليزي)", en: "Best Sellers Title (English)" },
    keywords: { ar: ["عنوان الأكثر مبيعاً إنجليزي"], en: ["best sellers title en"] },
  },
  {
    key: "homepage_editorial_sections",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "advanced",
    owner: "settings",
    type: "json",
    label: { ar: "أقسام الواجهة التحريرية والتسويقية", en: "Homepage Editorial Sections" },
    keywords: { ar: ["أقسام تسويقية", "بنرات", "افتتاحية"], en: ["editorial sections", "banners"] },
  },
  {
    key: "home_promo_cards",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "basic",
    owner: "settings",
    type: "json",
    label: { ar: "بطاقات العروض الترويجية في الواجهة", en: "Homepage Promo Cards" },
    keywords: { ar: ["بطاقات عروض", "ترويج"], en: ["promo cards", "promotions"] },
  },
  {
    key: "trending_banner_background_url",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "advanced",
    owner: "settings",
    type: "image",
    label: { ar: "صورة خلفية بنر التريند", en: "Trending Banner Background Image" },
    keywords: { ar: ["بنر تريند", "صورة بنر"], en: ["trending banner"] },
  },
  {
    key: "category_banner_background_url",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "advanced",
    owner: "settings",
    type: "image",
    label: { ar: "صورة خلفية بنر التصنيفات", en: "Category Banner Background Image" },
    keywords: { ar: ["بنر تصنيفات"], en: ["category banner"] },
  },
  {
    key: "secondary_banner_parallax_enabled",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "تفعيل تأثير البارالاكس للبنر الثانوي", en: "Enable Secondary Banner Parallax" },
    keywords: { ar: ["بارالاكس", "تأثير حركة"], en: ["parallax effect", "banner parallax"] },
  },
  {
    key: "secondary_banner_parallax_mobile_enabled",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "تفعيل بارالاكس البنر على الجوال", en: "Enable Parallax on Mobile" },
    keywords: { ar: ["بارالاكس جوال"], en: ["parallax mobile"] },
  },
  {
    key: "secondary_banner_parallax_breakpoint",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "نقطة توقف شاشة البارالاكس (px)", en: "Parallax Screen Breakpoint" },
    keywords: { ar: ["شاشة", "نقطة توقف"], en: ["breakpoint", "screen width"] },
  },
  {
    key: "global_sale_badges_enabled",
    table: "business_settings",
    tab: "storefront",
    group: "home_sections",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "تفعيل شارات التخفيضات التلقائية على المنتجات", en: "Enable Sale Badges on Products" },
    keywords: { ar: ["شارات تخفيض", "تنزيلات", "خصم"], en: ["sale badge", "discount tag"] },
  },

  // storefront.header_footer
  {
    key: "logo_size",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "حجم الشعار في الترويسة (px)", en: "Header Logo Height (px)" },
    keywords: { ar: ["حجم الشعار", "ارتفاع الشعار"], en: ["logo height", "header logo size"] },
  },
  {
    key: "logo_align",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "advanced",
    owner: "settings",
    type: "select",
    label: { ar: "محاذاة الشعار في الترويسة", en: "Header Logo Alignment" },
    keywords: { ar: ["محاذاة الشعار", "مكان الشعار"], en: ["logo align", "center logo"] },
  },
  {
    key: "show_header_name",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض اسم المتجر نصياً بجانب الشعار", en: "Show Store Name in Header" },
    keywords: { ar: ["اسم المتجر بالترويسة"], en: ["show store name header"] },
  },
  {
    key: "menu_title_en",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "عنوان القائمة (إنجليزي)", en: "Menu Title (English)" },
    keywords: { ar: ["عنوان القائمة"], en: ["menu title en"] },
  },
  {
    key: "menu_title_ar",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "عنوان القائمة (عربي)", en: "Menu Title (Arabic)" },
    keywords: { ar: ["عنوان القائمة عربي"], en: ["menu title ar"] },
  },
  {
    key: "menu_show_home",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "إظهار رابط الرئيسية في القائمة", en: "Show Home Link in Menu" },
    keywords: { ar: ["رابط الرئيسية"], en: ["menu show home"] },
  },
  {
    key: "menu_show_account",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "إظهار رابط الحساب في القائمة", en: "Show Account Link in Menu" },
    keywords: { ar: ["رابط الحساب"], en: ["menu show account"] },
  },
  {
    key: "menu_show_orders",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "إظهار رابط الطلبات في القائمة", en: "Show Orders Link in Menu" },
    keywords: { ar: ["رابط الطلبات"], en: ["menu show orders"] },
  },
  {
    key: "menu_show_pages",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "إظهار روابط الصفحات في القائمة", en: "Show Pages in Menu" },
    keywords: { ar: ["روابط الصفحات"], en: ["menu show pages"] },
  },
  {
    key: "footer_logo_size",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "حجم الشعار في التذييل (px)", en: "Footer Logo Height (px)" },
    keywords: { ar: ["شعار التذييل", "حجم شعار الفوتر"], en: ["footer logo size"] },
  },
  {
    key: "show_footer_name",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض اسم المتجر في التذييل", en: "Show Store Name in Footer" },
    keywords: { ar: ["اسم المتجر بالفوتر"], en: ["show footer store name"] },
  },
  {
    key: "trust_badges",
    table: "business_settings",
    tab: "storefront",
    group: "header_footer",
    level: "basic",
    owner: "settings",
    type: "json",
    label: { ar: "شارات الثقة والضمان (شحن سريع، أصلي، دفع آمن)", en: "Trust & Assurance Badges" },
    keywords: { ar: ["شارات ثقة", "ضمان", "أصلي", "شحن"], en: ["trust badges", "guarantee"] },
  },
  {
    key: "pages",
    table: "business_settings",
    tab: null,
    group: null,
    level: "advanced",
    owner: "route:pages",
    type: "json",
    label: { ar: "صفحات ومحتوى المتجر", en: "Store CMS Pages" },
    keywords: { ar: ["صفحات", "سياسات"], en: ["cms pages", "policy pages"] },
    readOnlyMirrors: ["admin.b.$slug.pages.tsx"],
  },

  // storefront.announcement
  {
    key: "announcement_enabled",
    table: "business_settings",
    tab: "storefront",
    group: "announcement",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "تفعيل شريط الإعلانات أعلى الصفحة", en: "Enable Announcement Bar" },
    keywords: { ar: ["إعلان", "شريط إعلان", "تنبيه أعلى"], en: ["announcement bar", "top banner"] },
  },
  {
    key: "announcement_text_ar",
    table: "business_settings",
    tab: "storefront",
    group: "announcement",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "نص الإعلان (عربي)", en: "Announcement Text (Arabic)" },
    keywords: { ar: ["نص الإعلان عربي"], en: ["announcement text arabic"] },
  },
  {
    key: "announcement_text_en",
    table: "business_settings",
    tab: "storefront",
    group: "announcement",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "نص الإعلان (إنجليزي)", en: "Announcement Text (English)" },
    keywords: { ar: ["نص الإعلان إنجليزي"], en: ["announcement text english"] },
  },
  {
    key: "announcement_bg",
    table: "business_settings",
    tab: "storefront",
    group: "announcement",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون خلفية شريط الإعلانات", en: "Announcement Background Color" },
    keywords: { ar: ["لون شريط الإعلان"], en: ["announcement bg"] },
  },
  {
    key: "announcement_fg",
    table: "business_settings",
    tab: "storefront",
    group: "announcement",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون نص شريط الإعلانات", en: "Announcement Text Color" },
    keywords: { ar: ["لون نص الإعلان"], en: ["announcement text color"] },
  },
  {
    key: "announcement_bold",
    table: "business_settings",
    tab: "storefront",
    group: "announcement",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "خط عريض لنص الإعلان", en: "Bold Announcement Text" },
    keywords: { ar: ["خط عريض"], en: ["bold text"] },
  },
  {
    key: "announcement_italic",
    table: "business_settings",
    tab: "storefront",
    group: "announcement",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "خط مائل لنص الإعلان", en: "Italic Announcement Text" },
    keywords: { ar: ["خط مائل"], en: ["italic text"] },
  },
  {
    key: "announcement_dismissible",
    table: "business_settings",
    tab: "storefront",
    group: "announcement",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "السماح للزائر بإغلاق شريط الإعلان", en: "Allow Dismissing Announcement" },
    keywords: { ar: ["إغلاق الإعلان"], en: ["dismiss announcement", "close banner"] },
  },
  {
    key: "announcement_scope",
    table: "business_settings",
    tab: "storefront",
    group: "announcement",
    level: "advanced",
    owner: "settings",
    type: "select",
    label: { ar: "نطاق ظهور الإعلان (كل الصفحات أو الرئيسية فقط)", en: "Announcement Page Scope" },
    keywords: { ar: ["نطاق الإعلان", "الرئيسية فقط"], en: ["announcement scope", "all pages"] },
  },
  {
    key: "announcement_audience",
    table: "business_settings",
    tab: "storefront",
    group: "announcement",
    level: "advanced",
    owner: "settings",
    type: "select",
    label: { ar: "الجمهور المستهدف لشريط الإعلان", en: "Announcement Audience" },
    keywords: { ar: ["جمهور الإعلان"], en: ["announcement audience"] },
  },

  // storefront.loader
  {
    key: "storefront_loader_text_ar",
    table: "business_settings",
    tab: "storefront",
    group: "loader",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "نص شاشة التحميل (عربي)", en: "Loading Screen Message (Arabic)" },
    keywords: { ar: ["شاشة تحميل", "جاري التحميل"], en: ["loading screen text ar"] },
  },
  {
    key: "storefront_loader_text_en",
    table: "business_settings",
    tab: "storefront",
    group: "loader",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "نص شاشة التحميل (إنجليزي)", en: "Loading Screen Message (English)" },
    keywords: { ar: ["شاشة تحميل إنجليزي"], en: ["loading screen text en"] },
  },

  // storefront.seo
  {
    key: "meta_title",
    table: "brands",
    tab: "storefront",
    group: "seo",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "عنوان المتجر في محركات البحث (Meta Title)", en: "SEO Meta Title" },
    keywords: { ar: ["سيو", "عنوان البحث", "قوقل"], en: ["seo", "meta title", "google title"] },
  },
  {
    key: "meta_description",
    table: "brands",
    tab: "storefront",
    group: "seo",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "وصف المتجر في محركات البحث (Meta Description)", en: "SEO Meta Description" },
    keywords: { ar: ["وصف البحث", "سيو", "قوقل"], en: ["seo", "meta description", "google snippet"] },
  },

  // ==========================================
  // ORDERS TAB
  // ==========================================

  // orders.payments
  {
    key: "cod_enabled",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "الدفع عند الاستلام (Cash on Delivery)", en: "Cash on Delivery (COD)" },
    keywords: { ar: ["دفع عند الاستلام", "كاش"], en: ["cod", "cash on delivery"] },
  },
  {
    key: "card_enabled",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "الدفع الإلكتروني بالبطاقات (Card)", en: "Credit/Debit Card Payments" },
    keywords: { ar: ["بطاقة", "فيزا", "مدى", "دفع إلكتروني"], en: ["card", "credit card", "debit"] },
  },
  {
    key: "card_public_key",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "المفتاح العام لبوابة الدفع (Card Public Key)", en: "Payment Gateway Public Key" },
    keywords: { ar: ["مفتاح عام", "بوابة دفع"], en: ["card public key"] },
  },
  {
    key: "card_secret_key",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "المفتاح السري لبوابة الدفع (Card Secret Key)", en: "Payment Gateway Secret Key" },
    keywords: { ar: ["مفتاح سري", "بوابة دفع"], en: ["card secret key"] },
  },
  {
    key: "card_processing_fee",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "رسوم معالجة الدفع بالبطاقة (%)", en: "Card Processing Fee (%)" },
    keywords: { ar: ["رسوم بطاقة", "نسبة معالجة"], en: ["card processing fee"] },
  },
  {
    key: "benefit_enabled",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "تفعيل الدفع عبر بنفت باي (BenefitPay)", en: "BenefitPay Payments" },
    keywords: { ar: ["بنفت", "بنفت باي", "تحويل"], en: ["benefit", "benefitpay"] },
  },
  {
    key: "benefit_qr_url",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "image",
    label: { ar: "رمز الاستجابة السريعة لبنفت (BenefitPay QR)", en: "BenefitPay QR Code Image" },
    keywords: { ar: ["باركود بنفت", "كيو ار بنفت"], en: ["benefit qr"] },
  },
  {
    key: "benefit_account_number",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "رقم هاتف أو حساب بنفت باي", en: "BenefitPay IBAN / Mobile Number" },
    keywords: { ar: ["رقم بنفت", "ايبان بنفت"], en: ["benefit account number", "iban"] },
  },
  {
    key: "benefit_processing_fee",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "رسوم معالجة بنفت باي", en: "BenefitPay Processing Fee" },
    keywords: { ar: ["رسوم بنفت"], en: ["benefit fee"] },
  },

  // orders.pricing
  {
    key: "currency",
    table: "business_settings",
    tab: "orders",
    group: "pricing",
    level: "basic",
    owner: "settings",
    type: "select",
    label: { ar: "عملة المتجر الرئيسية", en: "Store Base Currency" },
    keywords: { ar: ["عملة", "دينار", "ريال", "درهم"], en: ["currency", "bhd", "sar", "kwd"] },
  },
  {
    key: "default_tax_rate",
    table: "business_settings",
    tab: "orders",
    group: "pricing",
    level: "basic",
    owner: "settings",
    type: "number",
    label: { ar: "نسبة الضريبة الافتراضية (%)", en: "Default VAT Rate (%)" },
    keywords: { ar: ["ضريبة", "نسبة الضريبة", "قيمة مضافة"], en: ["vat rate", "tax percentage"] },
  },
  {
    key: "vat_inclusive",
    table: "business_settings",
    tab: "orders",
    group: "pricing",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "الأسعار المعروضة شاملة الضريبة", en: "Prices are VAT Inclusive" },
    keywords: { ar: ["شامل الضريبة", "ضريبة مضافة"], en: ["vat inclusive", "tax inclusive"] },
  },
  {
    key: "vat_number",
    table: "business_settings",
    tab: "orders",
    group: "pricing",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "الرقم الضريبي للمنشأة", en: "Tax / VAT Identification Number" },
    keywords: { ar: ["رقم ضريبي", "سجل ضريبي"], en: ["vat number", "tax id"] },
  },

  // orders.fulfillment
  {
    key: "delivery_enabled",
    table: "business_settings",
    tab: "orders",
    group: "fulfillment",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "تفعيل خيار التوصيل للمنازل", en: "Enable Home Delivery" },
    keywords: { ar: ["توصيل", "شحن"], en: ["delivery", "shipping"] },
  },
  {
    key: "pickup_enabled",
    table: "business_settings",
    tab: "orders",
    group: "fulfillment",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "تفعيل خيار الاستلام من الفرع", en: "Enable Store Pickup" },
    keywords: { ar: ["استلام", "فرع", "بيك اب"], en: ["pickup", "store pickup"] },
  },
  {
    key: "digital_delivery_enabled",
    table: "business_settings",
    tab: "orders",
    group: "fulfillment",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "تفعيل تسليم المنتجات الرقمية", en: "Enable Digital Product Delivery" },
    keywords: { ar: ["رقمي", "منتجات رقمية", "تحميل"], en: ["digital delivery", "download"] },
  },
  {
    key: "delivery_fee",
    table: "business_settings",
    tab: "orders",
    group: "fulfillment",
    level: "basic",
    owner: "settings",
    type: "number",
    label: { ar: "رسوم التوصيل الافتراضية", en: "Default Delivery Fee" },
    keywords: { ar: ["رسوم توصيل", "سعر التوصيل"], en: ["delivery fee", "shipping cost"] },
  },
  {
    key: "delivery_estimate_enabled",
    table: "business_settings",
    tab: "orders",
    group: "fulfillment",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض وقت التوصيل المتوقع للعميل", en: "Show Estimated Delivery Time" },
    keywords: { ar: ["وقت توصيل", "تقدير"], en: ["delivery estimate", "delivery time"] },
  },
  {
    key: "delivery_estimate_ar",
    table: "business_settings",
    tab: "orders",
    group: "fulfillment",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "مدة التوصيل المتوقعة (عربي)", en: "Estimated Delivery Text (Arabic)" },
    keywords: { ar: ["مدة التوصيل عربي"], en: ["delivery estimate ar"] },
  },
  {
    key: "delivery_estimate_en",
    table: "business_settings",
    tab: "orders",
    group: "fulfillment",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "مدة التوصيل المتوقعة (إنجليزي)", en: "Estimated Delivery Text (English)" },
    keywords: { ar: ["مدة التوصيل إنجليزي"], en: ["delivery estimate en"] },
  },
  {
    key: "shipping_zones",
    table: "business_settings",
    tab: "orders",
    group: "fulfillment",
    level: "basic",
    owner: "settings",
    type: "json",
    label: { ar: "مناطق ورسوم الشحن المخصصة", en: "Shipping Zones & Custom Rates" },
    keywords: { ar: ["مناطق شحن", "محافظات", "مدن", "تسعير شحن"], en: ["shipping zones", "delivery zones"] },
  },

  // orders.invoice
  {
    key: "invoice_template",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "basic",
    owner: "settings",
    type: "select",
    label: { ar: "قالب وتصميم الفاتورة", en: "Invoice Template Style" },
    keywords: { ar: ["قالب فاتورة", "شكل الفاتورة"], en: ["invoice template", "invoice style"] },
  },
  {
    key: "invoice_title_ar",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "عنوان الفاتورة الرئيسي (عربي)", en: "Invoice Title (Arabic)" },
    keywords: { ar: ["عنوان الفاتورة"], en: ["invoice title ar"] },
  },
  {
    key: "invoice_title_en",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "عنوان الفاتورة الرئيسي (إنجليزي)", en: "Invoice Title (English)" },
    keywords: { ar: ["عنوان الفاتورة إنجليزي"], en: ["invoice title en"] },
  },
  {
    key: "invoice_show_business_details",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض بيانات وسجل المتجر في الفاتورة", en: "Show Business Details on Invoice" },
    keywords: { ar: ["بيانات المتجر بالفاتورة"], en: ["show business details invoice"] },
  },
  {
    key: "invoice_show_business_name",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض اسم المتجر في الفاتورة", en: "Show Business Name on Invoice" },
    keywords: { ar: ["اسم المتجر بالفاتورة"], en: ["show business name invoice"] },
  },
  {
    key: "invoice_show_customer_contact",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض بيانات اتصال العميل في الفاتورة", en: "Show Customer Contact on Invoice" },
    keywords: { ar: ["بيانات العميل بالفاتورة"], en: ["show customer contact invoice"] },
  },
  {
    key: "invoice_show_fulfillment",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض طريقة التوصيل والاستلام في الفاتورة", en: "Show Fulfillment Method on Invoice" },
    keywords: { ar: ["طريقة التوصيل بالفاتورة"], en: ["show fulfillment invoice"] },
  },
  {
    key: "invoice_show_notes",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض ملاحظات الطلب في الفاتورة", en: "Show Order Notes on Invoice" },
    keywords: { ar: ["ملاحظات الطلب بالفاتورة"], en: ["show notes invoice"] },
  },
  {
    key: "invoice_show_terms",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "عرض الشروط والأحكام في الفاتورة", en: "Show Terms & Conditions on Invoice" },
    keywords: { ar: ["شروط الفاتورة", "أحكام الفاتورة"], en: ["show terms invoice"] },
  },
  {
    key: "invoice_terms_ar",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "شروط وأحكام الفاتورة (عربي)", en: "Invoice Terms & Conditions (Arabic)" },
    keywords: { ar: ["شروط الفاتورة عربي"], en: ["invoice terms ar"] },
  },
  {
    key: "invoice_terms_en",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "شروط وأحكام الفاتورة (إنجليزي)", en: "Invoice Terms & Conditions (English)" },
    keywords: { ar: ["شروط الفاتورة إنجليزي"], en: ["invoice terms en"] },
  },
  {
    key: "footer_note",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "الملاحظة الختامية في الفاتورة", en: "Invoice Footer Thank-You Note" },
    keywords: { ar: ["ملاحظة ختامية", "شكر"], en: ["invoice footer note"] },
  },
  {
    key: "invoice_inherit_brand_color",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "توريث لون العلامة تلقائياً في الفاتورة", en: "Inherit Brand Color in Invoice" },
    keywords: { ar: ["توريث لون الفاتورة", "لون الهوية"], en: ["inherit brand color invoice"] },
  },
  {
    key: "invoice_inherit_brand_font",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "توريث خطوط المتجر تلقائياً في الفاتورة", en: "Inherit Brand Fonts in Invoice" },
    keywords: { ar: ["توريث خط الفاتورة", "خط الهوية"], en: ["inherit brand font invoice"] },
  },
  {
    key: "primary_color",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "اللون الأساسي للفاتورة", en: "Invoice Primary Accent Color" },
    keywords: { ar: ["لون الفاتورة الأساسي"], en: ["invoice primary color"] },
  },
  {
    key: "invoice_secondary_color",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "اللون الثانوي للفاتورة", en: "Invoice Secondary Accent Color" },
    keywords: { ar: ["لون الفاتورة الثانوي"], en: ["invoice secondary color"] },
  },
  {
    key: "invoice_status_paid_color",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون شارة الفاتورة المدفوعة", en: "Invoice Paid Status Badge Color" },
    keywords: { ar: ["لون مدفوع"], en: ["invoice paid color"] },
  },
  {
    key: "invoice_status_unpaid_color",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون شارة الفاتورة غير المدفوعة", en: "Invoice Unpaid Status Badge Color" },
    keywords: { ar: ["لون غير مدفوع"], en: ["invoice unpaid color"] },
  },
  {
    key: "invoice_status_progress_color",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون شارة الفاتورة قيد التنفيذ", en: "Invoice In-Progress Status Badge Color" },
    keywords: { ar: ["لون قيد التنفيذ"], en: ["invoice in progress color"] },
  },
  {
    key: "invoice_table_header_bg",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "خلفية رأس جدول عناصر الفاتورة", en: "Invoice Table Header Background" },
    keywords: { ar: ["خلفية جدول الفاتورة"], en: ["invoice table header bg"] },
  },
  {
    key: "invoice_table_header_fg",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "نص رأس جدول عناصر الفاتورة", en: "Invoice Table Header Text" },
    keywords: { ar: ["نص رأس جدول الفاتورة"], en: ["invoice table header fg"] },
  },
  {
    key: "invoice_divider_color",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون الخطوط الفاصلة في الفاتورة", en: "Invoice Divider Lines Color" },
    keywords: { ar: ["فاصل الفاتورة"], en: ["invoice divider"] },
  },
  {
    key: "font_family",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "font",
    label: { ar: "الخط اللاتيني للفاتورة", en: "Invoice Latin Font Family" },
    keywords: { ar: ["خط الفاتورة اللاتيني"], en: ["invoice font family"] },
  },
  {
    key: "font_url",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "رابط خط الفاتورة المخصص", en: "Invoice Custom Font URL" },
    keywords: { ar: ["رابط خط الفاتورة"], en: ["invoice font url"] },
  },
  {
    key: "font_size",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "حجم خط الفاتورة الأساسي (pt)", en: "Invoice Base Font Size (pt)" },
    keywords: { ar: ["حجم خط الفاتورة"], en: ["invoice font size"] },
  },
  {
    key: "invoice_arabic_font_family",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "font",
    label: { ar: "الخط العربي للفاتورة", en: "Invoice Arabic Font Family" },
    keywords: { ar: ["خط الفاتورة العربي"], en: ["invoice arabic font"] },
  },
  {
    key: "text_color",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون نصوص الفاتورة العامة", en: "Invoice Body Text Color" },
    keywords: { ar: ["لون نص الفاتورة"], en: ["invoice text color"] },
  },
  {
    key: "background_color",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "color",
    label: { ar: "لون خلفية صفحة الفاتورة", en: "Invoice Page Background Color" },
    keywords: { ar: ["خلفية الفاتورة"], en: ["invoice background color"] },
  },
  {
    key: "logo_x",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "إزاحة الشعار الأفقية في الفاتورة (X)", en: "Invoice Logo Horizontal Offset (X)" },
    keywords: { ar: ["إزاحة الشعار"], en: ["logo x offset"] },
  },
  {
    key: "logo_y",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "إزاحة الشعار الرأسية في الفاتورة (Y)", en: "Invoice Logo Vertical Offset (Y)" },
    keywords: { ar: ["إزاحة الشعار رأسياً"], en: ["logo y offset"] },
  },
  {
    key: "logo_width",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "عرض الشعار في الفاتورة (px)", en: "Invoice Logo Width (px)" },
    keywords: { ar: ["عرض الشعار بالفاتورة"], en: ["logo width invoice"] },
  },
  {
    key: "logo_height",
    table: "business_settings",
    tab: "orders",
    group: "invoice",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "ارتفاع الشعار في الفاتورة (px)", en: "Invoice Logo Height (px)" },
    keywords: { ar: ["ارتفاع الشعار بالفاتورة"], en: ["logo height invoice"] },
  },
  {
    key: "next_invoice_number",
    table: "business_settings",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "number",
    label: { ar: "رقم الفاتورة التالي (تسلسلي تلقائي)", en: "Next Invoice Number (Auto Sequence)" },
    keywords: { ar: ["رقم الفاتورة التالي"], en: ["next invoice number"] },
  },

  // ==========================================
  // NOTIFICATIONS TAB
  // ==========================================

  // notifications.templates
  {
    key: "email_sender_name",
    table: "business_settings",
    tab: "notifications",
    group: "templates",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "اسم مرسل رسائل البريد الإلكتروني", en: "Sender Display Name" },
    keywords: { ar: ["اسم المرسل", "مرسل البريد"], en: ["sender name", "email from"] },
  },
  {
    key: "email_intro_ar",
    table: "business_settings",
    tab: "notifications",
    group: "templates",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "مقدمة بريد تأكيد الطلب (عربي)", en: "Order Email Greeting / Intro (Arabic)" },
    keywords: { ar: ["مقدمة البريد", "تأكيد الطلب"], en: ["email intro arabic"] },
  },
  {
    key: "email_intro_en",
    table: "business_settings",
    tab: "notifications",
    group: "templates",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "مقدمة بريد تأكيد الطلب (إنجليزي)", en: "Order Email Greeting / Intro (English)" },
    keywords: { ar: ["مقدمة البريد إنجليزي"], en: ["email intro english"] },
  },
  {
    key: "email_footer_ar",
    table: "business_settings",
    tab: "notifications",
    group: "templates",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "خاتمة بريد تأكيد الطلب (عربي)", en: "Order Email Sign-off / Footer (Arabic)" },
    keywords: { ar: ["خاتمة البريد"], en: ["email footer arabic"] },
  },
  {
    key: "email_footer_en",
    table: "business_settings",
    tab: "notifications",
    group: "templates",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "خاتمة بريد تأكيد الطلب (إنجليزي)", en: "Order Email Sign-off / Footer (English)" },
    keywords: { ar: ["خاتمة البريد إنجليزي"], en: ["email footer english"] },
  },
  {
    key: "courier_out_for_delivery_message_ar",
    table: "business_settings",
    tab: "notifications",
    group: "templates",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "رسالة السائق: الطلب خرج للتوصيل (عربي)", en: "Courier Out for Delivery SMS / WhatsApp (Arabic)" },
    keywords: { ar: ["رسالة سائق", "خرج للتوصيل"], en: ["courier delivery message arabic"] },
  },
  {
    key: "courier_out_for_delivery_message_en",
    table: "business_settings",
    tab: "notifications",
    group: "templates",
    level: "advanced",
    owner: "settings",
    type: "textarea",
    label: { ar: "رسالة السائق: الطلب خرج للتوصيل (إنجليزي)", en: "Courier Out for Delivery SMS / WhatsApp (English)" },
    keywords: { ar: ["رسالة سائق إنجليزي"], en: ["courier delivery message english"] },
  },

  // ==========================================
  // ACCOUNT TAB
  // ==========================================

  // account.security
  {
    key: "support_access_enabled",
    table: "brands",
    tab: "account",
    group: "security",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "السماح بالدعم الفني المباشر لحسابك", en: "Allow Boutq Support Access" },
    keywords: { ar: ["دعم فني", "مساعدة", "أمان"], en: ["support access", "technical help"] },
  },

  // account.subscription (system / managed via billing)
  {
    key: "plan_type",
    table: "brands",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "select",
    label: { ar: "نوع الباقة والاشتراك", en: "Subscription Plan Type" },
    keywords: { ar: ["باقة", "اشتراك"], en: ["plan type", "subscription"] },
  },
  {
    key: "subscription_tier",
    table: "brands",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "select",
    label: { ar: "مستوى الاشتراك", en: "Subscription Tier" },
    keywords: { ar: ["مستوى الاشتراك"], en: ["subscription tier"] },
  },
  {
    key: "subscription_status",
    table: "brands",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "select",
    label: { ar: "حالة الاشتراك", en: "Subscription Status" },
    keywords: { ar: ["حالة الاشتراك"], en: ["subscription status"] },
  },
  {
    key: "subscription_expires_at",
    table: "brands",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "text",
    label: { ar: "تاريخ انتهاء الاشتراك", en: "Subscription Expiration Date" },
    keywords: { ar: ["تاريخ انتهاء"], en: ["subscription expiry"] },
  },
  {
    key: "trial_ends_at",
    table: "brands",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "text",
    label: { ar: "تاريخ انتهاء الفترة التجريبية", en: "Trial End Date" },
    keywords: { ar: ["فترة تجريبية"], en: ["trial end"] },
  },
  {
    key: "renewal_intent",
    table: "brands",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "select",
    label: { ar: "نية تجديد الاشتراك", en: "Renewal Intent" },
    keywords: { ar: ["تجديد"], en: ["renewal intent"] },
  },
  {
    key: "renewal_intent_recorded_at",
    table: "brands",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "text",
    label: { ar: "وقت تسجيل نية التجديد", en: "Renewal Intent Recorded At" },
    keywords: { ar: ["وقت التجديد"], en: ["renewal recorded at"] },
  },

  // ==========================================
  // SYSTEM COLUMNS & OTHER ROUTE OWNERS
  // ==========================================
  {
    key: "brand_id",
    table: "business_settings",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "text",
    label: { ar: "معرّف العلامة التجارية", en: "Brand Identifier" },
    keywords: { ar: ["معرف", "براند"], en: ["brand id"] },
  },
  {
    key: "user_id",
    table: "business_settings",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "text",
    label: { ar: "معرّف مالك الحساب", en: "Owner User Identifier" },
    keywords: { ar: ["مستخدم", "مالك"], en: ["user id"] },
  },
  {
    key: "created_at",
    table: "business_settings",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "text",
    label: { ar: "تاريخ الإنشاء", en: "Created At" },
    keywords: { ar: ["إنشاء", "تاريخ"], en: ["created at"] },
  },
  {
    key: "updated_at",
    table: "business_settings",
    tab: null,
    group: null,
    level: "advanced",
    owner: "system",
    type: "text",
    label: { ar: "تاريخ آخر تحديث", en: "Updated At" },
    keywords: { ar: ["تحديث"], en: ["updated at"] },
  },
  {
    key: "bom_enabled",
    table: "business_settings",
    tab: null,
    group: null,
    level: "advanced",
    owner: "route:expenses",
    type: "boolean",
    label: { ar: "تفعيل جدول تكلفة المواد (BOM)", en: "Bill of Materials (BOM) Calculation" },
    keywords: { ar: ["تكلفة المواد", "تصنيع", "مصروفات"], en: ["bom", "bill of materials", "cogs"] },
    readOnlyMirrors: ["admin.b.$slug.expenses.tsx"],
  },
];
