import type { SettingsFieldDef } from "@/features/settings/registry";

/**
 * The Orders tab's payments group (cash on delivery, cards, BenefitPay, processing fees and
 * the advance-payment rule), kept apart so the registry file does not grow. SETTINGS_REGISTRY
 * spreads it in at the same place, so the order of fields is unchanged.
 */
export const PAYMENTS_SETTINGS: SettingsFieldDef[] = [
  {
    key: "cod_enabled",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "الدفع عند الاستلام (Cash on Delivery)", en: "Cash on Delivery (COD)" },
    keywords: { ar: ["دفع عند الاستلام", "كاش"], en: ["cod", "cash on delivery"] },
  },
  {
    key: "card_enabled",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "الدفع الإلكتروني بالبطاقات (Card)", en: "Credit/Debit Card Payments" },
    keywords: {
      ar: ["بطاقة", "فيزا", "مدى", "دفع إلكتروني"],
      en: ["card", "credit card", "debit"],
    },
  },
  {
    key: "advance_payment_enabled",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: { ar: "اشتراط دفعة مقدمة لإتمام الطلب", en: "Require an advance payment" },
    keywords: {
      ar: ["دفعة مقدمة", "عربون", "دفع مسبق", "دفعة أولى"],
      en: ["advance payment", "deposit", "prepayment", "down payment"],
    },
  },
  {
    key: "advance_payment_scope",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "select",
    label: {
      ar: "الطلبات التي تنطبق عليها الدفعة المقدمة",
      en: "Orders the advance payment applies to",
    },
    keywords: {
      ar: ["نطاق الدفعة المقدمة", "تفصيل فقط", "توصيل فقط", "حسب الطلب"],
      en: ["advance scope", "made to order only", "delivery only", "tailoring"],
    },
  },
  {
    key: "advance_payment_percent",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "نسبة الدفعة المقدمة (%)", en: "Advance payment share (%)" },
    keywords: {
      ar: ["نسبة الدفعة المقدمة", "نسبة العربون"],
      en: ["advance percentage", "deposit percent"],
    },
  },
  {
    key: "advance_allow_full_payment",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "boolean",
    label: {
      ar: "السماح للعميل بدفع المبلغ كاملاً بدل الدفعة المقدمة",
      en: "Let customers pay the full amount instead of the advance",
    },
    keywords: {
      ar: ["دفع كامل", "دفع المبلغ كاملاً", "دفعة مقدمة"],
      en: ["pay in full", "full payment", "advance payment"],
    },
  },
  {
    key: "card_public_key",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "المفتاح العام لبوابة الدفع (Card Public Key)", en: "Payment Gateway Public Key" },
    keywords: { ar: ["مفتاح عام", "بوابة دفع"], en: ["card public key"] },
  },
  {
    key: "card_secret_key",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "text",
    label: { ar: "المفتاح السري لبوابة الدفع (Card Secret Key)", en: "Payment Gateway Secret Key" },
    keywords: { ar: ["مفتاح سري", "بوابة دفع"], en: ["card secret key"] },
  },
  {
    key: "card_processing_fee",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "رسوم معالجة الدفع بالبطاقة (%)", en: "Card Processing Fee (%)" },
    keywords: { ar: ["رسوم بطاقة", "نسبة معالجة"], en: ["card processing fee"] },
  },
  {
    key: "benefit_enabled",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "basic",
    owner: "settings",
    type: "boolean",
    label: { ar: "تفعيل الدفع عبر بنفت باي (BenefitPay)", en: "BenefitPay Payments" },
    keywords: { ar: ["بنفت", "بنفت باي", "تحويل"], en: ["benefit", "benefitpay"] },
  },
  {
    key: "benefit_qr_url",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "image",
    label: { ar: "رمز الاستجابة السريعة لبنفت (BenefitPay QR)", en: "BenefitPay QR Code Image" },
    keywords: { ar: ["باركود بنفت", "كيو ار بنفت"], en: ["benefit qr"] },
  },
  {
    key: "benefit_account_number",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "basic",
    owner: "settings",
    type: "text",
    label: { ar: "رقم هاتف أو حساب بنفت باي", en: "BenefitPay IBAN / Mobile Number" },
    keywords: { ar: ["رقم بنفت", "ايبان بنفت"], en: ["benefit account number", "iban"] },
  },
  {
    key: "benefit_processing_fee",
    table: "business_settings",
    tab: "orders",
    group: "payments",
    level: "advanced",
    owner: "settings",
    type: "number",
    label: { ar: "رسوم معالجة بنفت باي", en: "BenefitPay Processing Fee" },
    keywords: { ar: ["رسوم بنفت"], en: ["benefit fee"] },
  },
];
