/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as StoreSlugRouteRouteImport } from './routes/store.$slug.route'
import { Route as StoreSlugIndexRouteImport } from './routes/store.$slug.index'
import { Route as StoreSlugSearchRouteImport } from './routes/store.$slug.search'
import { Route as StoreSlugCheckoutRouteImport } from './routes/store.$slug.checkout'
import { Route as StoreSlugAuthRouteImport } from './routes/store.$slug.auth'
import { Route as AuthenticatedBSlugRouteRouteImport } from './routes/_authenticated/b.$slug.route'
import { Route as StoreSlugThankYouOrderIdRouteImport } from './routes/store.$slug.thank-you.$orderId'
import { Route as StoreSlugProductIdRouteImport } from './routes/store.$slug.product.$id'
import { Route as StoreSlugPageIdxRouteImport } from './routes/store.$slug.page.$idx'
import { Route as AuthenticatedBSlugTeamRouteImport } from './routes/_authenticated/b.$slug.team'
import { Route as AuthenticatedBSlugSettingsRouteImport } from './routes/_authenticated/b.$slug.settings'
import { Route as AuthenticatedBSlugPagesRouteImport } from './routes/_authenticated/b.$slug.pages'
import { Route as AuthenticatedBSlugInventoryRouteImport } from './routes/_authenticated/b.$slug.inventory'
import { Route as AuthenticatedBSlugIntegrationsRouteImport } from './routes/_authenticated/b.$slug.integrations'
import { Route as AuthenticatedBSlugExpensesRouteImport } from './routes/_authenticated/b.$slug.expenses'
import { Route as AuthenticatedBSlugDashboardRouteImport } from './routes/_authenticated/b.$slug.dashboard'
import { Route as AuthenticatedBSlugCustomersRouteImport } from './routes/_authenticated/b.$slug.customers'
import { Route as AuthenticatedBSlugCategoriesRouteImport } from './routes/_authenticated/b.$slug.categories'
import { Route as AuthenticatedBSlugCampaignsRouteImport } from './routes/_authenticated/b.$slug.campaigns'
import { Route as AuthenticatedBSlugOrdersIndexRouteImport } from './routes/_authenticated/b.$slug.orders.index'
import { Route as AuthenticatedBSlugOrdersIdRouteImport } from './routes/_authenticated/b.$slug.orders.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const StoreSlugRouteRoute = StoreSlugRouteRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugIndexRoute = StoreSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreSlugRouteRoute,
} as any)
const StoreSlugSearchRoute = StoreSlugSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => StoreSlugRouteRoute,
} as any)
const StoreSlugCheckoutRoute = StoreSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreSlugRouteRoute,
} as any)
const StoreSlugAuthRoute = StoreSlugAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => StoreSlugRouteRoute,
} as any)
const AuthenticatedBSlugRouteRoute = AuthenticatedBSlugRouteRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const StoreSlugThankYouOrderIdRoute =
  StoreSlugThankYouOrderIdRouteImport.update({
    id: '/thank-you/$orderId',
    path: '/thank-you/$orderId',
    getParentRoute: () => StoreSlugRouteRoute,
  } as any)
const StoreSlugProductIdRoute = StoreSlugProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => StoreSlugRouteRoute,
} as any)
const StoreSlugPageIdxRoute = StoreSlugPageIdxRouteImport.update({
  id: '/page/$idx',
  path: '/page/$idx',
  getParentRoute: () => StoreSlugRouteRoute,
} as any)
const AuthenticatedBSlugTeamRoute = AuthenticatedBSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedBSlugRouteRoute,
} as any)
const AuthenticatedBSlugSettingsRoute =
  AuthenticatedBSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedBSlugRouteRoute,
  } as any)
const AuthenticatedBSlugPagesRoute = AuthenticatedBSlugPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedBSlugRouteRoute,
} as any)
const AuthenticatedBSlugInventoryRoute =
  AuthenticatedBSlugInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedBSlugRouteRoute,
  } as any)
const AuthenticatedBSlugIntegrationsRoute =
  AuthenticatedBSlugIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedBSlugRouteRoute,
  } as any)
const AuthenticatedBSlugExpensesRoute =
  AuthenticatedBSlugExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedBSlugRouteRoute,
  } as any)
const AuthenticatedBSlugDashboardRoute =
  AuthenticatedBSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedBSlugRouteRoute,
  } as any)
const AuthenticatedBSlugCustomersRoute =
  AuthenticatedBSlugCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedBSlugRouteRoute,
  } as any)
const AuthenticatedBSlugCategoriesRoute =
  AuthenticatedBSlugCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedBSlugRouteRoute,
  } as any)
const AuthenticatedBSlugCampaignsRoute =
  AuthenticatedBSlugCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedBSlugRouteRoute,
  } as any)
const AuthenticatedBSlugOrdersIndexRoute =
  AuthenticatedBSlugOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedBSlugRouteRoute,
  } as any)
const AuthenticatedBSlugOrdersIdRoute =
  AuthenticatedBSlugOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => AuthenticatedBSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/store/$slug': typeof StoreSlugRouteRouteWithChildren
  '/brands': typeof AuthenticatedBrandsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/b/$slug': typeof AuthenticatedBSlugRouteRouteWithChildren
  '/store/$slug/auth': typeof StoreSlugAuthRoute
  '/store/$slug/checkout': typeof StoreSlugCheckoutRoute
  '/store/$slug/search': typeof StoreSlugSearchRoute
  '/store/$slug/': typeof StoreSlugIndexRoute
  '/b/$slug/campaigns': typeof AuthenticatedBSlugCampaignsRoute
  '/b/$slug/categories': typeof AuthenticatedBSlugCategoriesRoute
  '/b/$slug/customers': typeof AuthenticatedBSlugCustomersRoute
  '/b/$slug/dashboard': typeof AuthenticatedBSlugDashboardRoute
  '/b/$slug/expenses': typeof AuthenticatedBSlugExpensesRoute
  '/b/$slug/integrations': typeof AuthenticatedBSlugIntegrationsRoute
  '/b/$slug/inventory': typeof AuthenticatedBSlugInventoryRoute
  '/b/$slug/pages': typeof AuthenticatedBSlugPagesRoute
  '/b/$slug/settings': typeof AuthenticatedBSlugSettingsRoute
  '/b/$slug/team': typeof AuthenticatedBSlugTeamRoute
  '/store/$slug/page/$idx': typeof StoreSlugPageIdxRoute
  '/store/$slug/product/$id': typeof StoreSlugProductIdRoute
  '/store/$slug/thank-you/$orderId': typeof StoreSlugThankYouOrderIdRoute
  '/b/$slug/orders/$id': typeof AuthenticatedBSlugOrdersIdRoute
  '/b/$slug/orders/': typeof AuthenticatedBSlugOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/b/$slug': typeof AuthenticatedBSlugRouteRouteWithChildren
  '/store/$slug/auth': typeof StoreSlugAuthRoute
  '/store/$slug/checkout': typeof StoreSlugCheckoutRoute
  '/store/$slug/search': typeof StoreSlugSearchRoute
  '/store/$slug': typeof StoreSlugIndexRoute
  '/b/$slug/campaigns': typeof AuthenticatedBSlugCampaignsRoute
  '/b/$slug/categories': typeof AuthenticatedBSlugCategoriesRoute
  '/b/$slug/customers': typeof AuthenticatedBSlugCustomersRoute
  '/b/$slug/dashboard': typeof AuthenticatedBSlugDashboardRoute
  '/b/$slug/expenses': typeof AuthenticatedBSlugExpensesRoute
  '/b/$slug/integrations': typeof AuthenticatedBSlugIntegrationsRoute
  '/b/$slug/inventory': typeof AuthenticatedBSlugInventoryRoute
  '/b/$slug/pages': typeof AuthenticatedBSlugPagesRoute
  '/b/$slug/settings': typeof AuthenticatedBSlugSettingsRoute
  '/b/$slug/team': typeof AuthenticatedBSlugTeamRoute
  '/store/$slug/page/$idx': typeof StoreSlugPageIdxRoute
  '/store/$slug/product/$id': typeof StoreSlugProductIdRoute
  '/store/$slug/thank-you/$orderId': typeof StoreSlugThankYouOrderIdRoute
  '/b/$slug/orders/$id': typeof AuthenticatedBSlugOrdersIdRoute
  '/b/$slug/orders': typeof AuthenticatedBSlugOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/store/$slug': typeof StoreSlugRouteRouteWithChildren
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/_authenticated/b/$slug': typeof AuthenticatedBSlugRouteRouteWithChildren
  '/store/$slug/auth': typeof StoreSlugAuthRoute
  '/store/$slug/checkout': typeof StoreSlugCheckoutRoute
  '/store/$slug/search': typeof StoreSlugSearchRoute
  '/store/$slug/': typeof StoreSlugIndexRoute
  '/_authenticated/b/$slug/campaigns': typeof AuthenticatedBSlugCampaignsRoute
  '/_authenticated/b/$slug/categories': typeof AuthenticatedBSlugCategoriesRoute
  '/_authenticated/b/$slug/customers': typeof AuthenticatedBSlugCustomersRoute
  '/_authenticated/b/$slug/dashboard': typeof AuthenticatedBSlugDashboardRoute
  '/_authenticated/b/$slug/expenses': typeof AuthenticatedBSlugExpensesRoute
  '/_authenticated/b/$slug/integrations': typeof AuthenticatedBSlugIntegrationsRoute
  '/_authenticated/b/$slug/inventory': typeof AuthenticatedBSlugInventoryRoute
  '/_authenticated/b/$slug/pages': typeof AuthenticatedBSlugPagesRoute
  '/_authenticated/b/$slug/settings': typeof AuthenticatedBSlugSettingsRoute
  '/_authenticated/b/$slug/team': typeof AuthenticatedBSlugTeamRoute
  '/store/$slug/page/$idx': typeof StoreSlugPageIdxRoute
  '/store/$slug/product/$id': typeof StoreSlugProductIdRoute
  '/store/$slug/thank-you/$orderId': typeof StoreSlugThankYouOrderIdRoute
  '/_authenticated/b/$slug/orders/$id': typeof AuthenticatedBSlugOrdersIdRoute
  '/_authenticated/b/$slug/orders/': typeof AuthenticatedBSlugOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/store/$slug'
    | '/brands'
    | '/campaigns'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/inventory'
    | '/orders'
    | '/settings'
    | '/team'
    | '/invoice/$id'
    | '/b/$slug'
    | '/store/$slug/auth'
    | '/store/$slug/checkout'
    | '/store/$slug/search'
    | '/store/$slug/'
    | '/b/$slug/campaigns'
    | '/b/$slug/categories'
    | '/b/$slug/customers'
    | '/b/$slug/dashboard'
    | '/b/$slug/expenses'
    | '/b/$slug/integrations'
    | '/b/$slug/inventory'
    | '/b/$slug/pages'
    | '/b/$slug/settings'
    | '/b/$slug/team'
    | '/store/$slug/page/$idx'
    | '/store/$slug/product/$id'
    | '/store/$slug/thank-you/$orderId'
    | '/b/$slug/orders/$id'
    | '/b/$slug/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/brands'
    | '/campaigns'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/inventory'
    | '/orders'
    | '/settings'
    | '/team'
    | '/invoice/$id'
    | '/b/$slug'
    | '/store/$slug/auth'
    | '/store/$slug/checkout'
    | '/store/$slug/search'
    | '/store/$slug'
    | '/b/$slug/campaigns'
    | '/b/$slug/categories'
    | '/b/$slug/customers'
    | '/b/$slug/dashboard'
    | '/b/$slug/expenses'
    | '/b/$slug/integrations'
    | '/b/$slug/inventory'
    | '/b/$slug/pages'
    | '/b/$slug/settings'
    | '/b/$slug/team'
    | '/store/$slug/page/$idx'
    | '/store/$slug/product/$id'
    | '/store/$slug/thank-you/$orderId'
    | '/b/$slug/orders/$id'
    | '/b/$slug/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/store/$slug'
    | '/_authenticated/brands'
    | '/_authenticated/campaigns'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/inventory'
    | '/_authenticated/orders'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/invoice/$id'
    | '/_authenticated/b/$slug'
    | '/store/$slug/auth'
    | '/store/$slug/checkout'
    | '/store/$slug/search'
    | '/store/$slug/'
    | '/_authenticated/b/$slug/campaigns'
    | '/_authenticated/b/$slug/categories'
    | '/_authenticated/b/$slug/customers'
    | '/_authenticated/b/$slug/dashboard'
    | '/_authenticated/b/$slug/expenses'
    | '/_authenticated/b/$slug/integrations'
    | '/_authenticated/b/$slug/inventory'
    | '/_authenticated/b/$slug/pages'
    | '/_authenticated/b/$slug/settings'
    | '/_authenticated/b/$slug/team'
    | '/store/$slug/page/$idx'
    | '/store/$slug/product/$id'
    | '/store/$slug/thank-you/$orderId'
    | '/_authenticated/b/$slug/orders/$id'
    | '/_authenticated/b/$slug/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StoreSlugRouteRoute: typeof StoreSlugRouteRouteWithChildren
  InvoiceIdRoute: typeof InvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug/': {
      id: '/store/$slug/'
      path: '/'
      fullPath: '/store/$slug/'
      preLoaderRoute: typeof StoreSlugIndexRouteImport
      parentRoute: typeof StoreSlugRouteRoute
    }
    '/store/$slug/search': {
      id: '/store/$slug/search'
      path: '/search'
      fullPath: '/store/$slug/search'
      preLoaderRoute: typeof StoreSlugSearchRouteImport
      parentRoute: typeof StoreSlugRouteRoute
    }
    '/store/$slug/checkout': {
      id: '/store/$slug/checkout'
      path: '/checkout'
      fullPath: '/store/$slug/checkout'
      preLoaderRoute: typeof StoreSlugCheckoutRouteImport
      parentRoute: typeof StoreSlugRouteRoute
    }
    '/store/$slug/auth': {
      id: '/store/$slug/auth'
      path: '/auth'
      fullPath: '/store/$slug/auth'
      preLoaderRoute: typeof StoreSlugAuthRouteImport
      parentRoute: typeof StoreSlugRouteRoute
    }
    '/_authenticated/b/$slug': {
      id: '/_authenticated/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof AuthenticatedBSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/store/$slug/thank-you/$orderId': {
      id: '/store/$slug/thank-you/$orderId'
      path: '/thank-you/$orderId'
      fullPath: '/store/$slug/thank-you/$orderId'
      preLoaderRoute: typeof StoreSlugThankYouOrderIdRouteImport
      parentRoute: typeof StoreSlugRouteRoute
    }
    '/store/$slug/product/$id': {
      id: '/store/$slug/product/$id'
      path: '/product/$id'
      fullPath: '/store/$slug/product/$id'
      preLoaderRoute: typeof StoreSlugProductIdRouteImport
      parentRoute: typeof StoreSlugRouteRoute
    }
    '/store/$slug/page/$idx': {
      id: '/store/$slug/page/$idx'
      path: '/page/$idx'
      fullPath: '/store/$slug/page/$idx'
      preLoaderRoute: typeof StoreSlugPageIdxRouteImport
      parentRoute: typeof StoreSlugRouteRoute
    }
    '/_authenticated/b/$slug/team': {
      id: '/_authenticated/b/$slug/team'
      path: '/team'
      fullPath: '/b/$slug/team'
      preLoaderRoute: typeof AuthenticatedBSlugTeamRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
    '/_authenticated/b/$slug/settings': {
      id: '/_authenticated/b/$slug/settings'
      path: '/settings'
      fullPath: '/b/$slug/settings'
      preLoaderRoute: typeof AuthenticatedBSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
    '/_authenticated/b/$slug/pages': {
      id: '/_authenticated/b/$slug/pages'
      path: '/pages'
      fullPath: '/b/$slug/pages'
      preLoaderRoute: typeof AuthenticatedBSlugPagesRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
    '/_authenticated/b/$slug/inventory': {
      id: '/_authenticated/b/$slug/inventory'
      path: '/inventory'
      fullPath: '/b/$slug/inventory'
      preLoaderRoute: typeof AuthenticatedBSlugInventoryRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
    '/_authenticated/b/$slug/integrations': {
      id: '/_authenticated/b/$slug/integrations'
      path: '/integrations'
      fullPath: '/b/$slug/integrations'
      preLoaderRoute: typeof AuthenticatedBSlugIntegrationsRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
    '/_authenticated/b/$slug/expenses': {
      id: '/_authenticated/b/$slug/expenses'
      path: '/expenses'
      fullPath: '/b/$slug/expenses'
      preLoaderRoute: typeof AuthenticatedBSlugExpensesRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
    '/_authenticated/b/$slug/dashboard': {
      id: '/_authenticated/b/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/b/$slug/dashboard'
      preLoaderRoute: typeof AuthenticatedBSlugDashboardRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
    '/_authenticated/b/$slug/customers': {
      id: '/_authenticated/b/$slug/customers'
      path: '/customers'
      fullPath: '/b/$slug/customers'
      preLoaderRoute: typeof AuthenticatedBSlugCustomersRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
    '/_authenticated/b/$slug/categories': {
      id: '/_authenticated/b/$slug/categories'
      path: '/categories'
      fullPath: '/b/$slug/categories'
      preLoaderRoute: typeof AuthenticatedBSlugCategoriesRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
    '/_authenticated/b/$slug/campaigns': {
      id: '/_authenticated/b/$slug/campaigns'
      path: '/campaigns'
      fullPath: '/b/$slug/campaigns'
      preLoaderRoute: typeof AuthenticatedBSlugCampaignsRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
    '/_authenticated/b/$slug/orders/': {
      id: '/_authenticated/b/$slug/orders/'
      path: '/orders'
      fullPath: '/b/$slug/orders/'
      preLoaderRoute: typeof AuthenticatedBSlugOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
    '/_authenticated/b/$slug/orders/$id': {
      id: '/_authenticated/b/$slug/orders/$id'
      path: '/orders/$id'
      fullPath: '/b/$slug/orders/$id'
      preLoaderRoute: typeof AuthenticatedBSlugOrdersIdRouteImport
      parentRoute: typeof AuthenticatedBSlugRouteRoute
    }
  }
}

interface AuthenticatedBSlugRouteRouteChildren {
  AuthenticatedBSlugCampaignsRoute: typeof AuthenticatedBSlugCampaignsRoute
  AuthenticatedBSlugCategoriesRoute: typeof AuthenticatedBSlugCategoriesRoute
  AuthenticatedBSlugCustomersRoute: typeof AuthenticatedBSlugCustomersRoute
  AuthenticatedBSlugDashboardRoute: typeof AuthenticatedBSlugDashboardRoute
  AuthenticatedBSlugExpensesRoute: typeof AuthenticatedBSlugExpensesRoute
  AuthenticatedBSlugIntegrationsRoute: typeof AuthenticatedBSlugIntegrationsRoute
  AuthenticatedBSlugInventoryRoute: typeof AuthenticatedBSlugInventoryRoute
  AuthenticatedBSlugPagesRoute: typeof AuthenticatedBSlugPagesRoute
  AuthenticatedBSlugSettingsRoute: typeof AuthenticatedBSlugSettingsRoute
  AuthenticatedBSlugTeamRoute: typeof AuthenticatedBSlugTeamRoute
  AuthenticatedBSlugOrdersIdRoute: typeof AuthenticatedBSlugOrdersIdRoute
  AuthenticatedBSlugOrdersIndexRoute: typeof AuthenticatedBSlugOrdersIndexRoute
}

const AuthenticatedBSlugRouteRouteChildren: AuthenticatedBSlugRouteRouteChildren =
  {
    AuthenticatedBSlugCampaignsRoute: AuthenticatedBSlugCampaignsRoute,
    AuthenticatedBSlugCategoriesRoute: AuthenticatedBSlugCategoriesRoute,
    AuthenticatedBSlugCustomersRoute: AuthenticatedBSlugCustomersRoute,
    AuthenticatedBSlugDashboardRoute: AuthenticatedBSlugDashboardRoute,
    AuthenticatedBSlugExpensesRoute: AuthenticatedBSlugExpensesRoute,
    AuthenticatedBSlugIntegrationsRoute: AuthenticatedBSlugIntegrationsRoute,
    AuthenticatedBSlugInventoryRoute: AuthenticatedBSlugInventoryRoute,
    AuthenticatedBSlugPagesRoute: AuthenticatedBSlugPagesRoute,
    AuthenticatedBSlugSettingsRoute: AuthenticatedBSlugSettingsRoute,
    AuthenticatedBSlugTeamRoute: AuthenticatedBSlugTeamRoute,
    AuthenticatedBSlugOrdersIdRoute: AuthenticatedBSlugOrdersIdRoute,
    AuthenticatedBSlugOrdersIndexRoute: AuthenticatedBSlugOrdersIndexRoute,
  }

const AuthenticatedBSlugRouteRouteWithChildren =
  AuthenticatedBSlugRouteRoute._addFileChildren(
    AuthenticatedBSlugRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedBSlugRouteRoute: typeof AuthenticatedBSlugRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedBSlugRouteRoute: AuthenticatedBSlugRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StoreSlugRouteRouteChildren {
  StoreSlugAuthRoute: typeof StoreSlugAuthRoute
  StoreSlugCheckoutRoute: typeof StoreSlugCheckoutRoute
  StoreSlugSearchRoute: typeof StoreSlugSearchRoute
  StoreSlugIndexRoute: typeof StoreSlugIndexRoute
  StoreSlugPageIdxRoute: typeof StoreSlugPageIdxRoute
  StoreSlugProductIdRoute: typeof StoreSlugProductIdRoute
  StoreSlugThankYouOrderIdRoute: typeof StoreSlugThankYouOrderIdRoute
}

const StoreSlugRouteRouteChildren: StoreSlugRouteRouteChildren = {
  StoreSlugAuthRoute: StoreSlugAuthRoute,
  StoreSlugCheckoutRoute: StoreSlugCheckoutRoute,
  StoreSlugSearchRoute: StoreSlugSearchRoute,
  StoreSlugIndexRoute: StoreSlugIndexRoute,
  StoreSlugPageIdxRoute: StoreSlugPageIdxRoute,
  StoreSlugProductIdRoute: StoreSlugProductIdRoute,
  StoreSlugThankYouOrderIdRoute: StoreSlugThankYouOrderIdRoute,
}

const StoreSlugRouteRouteWithChildren = StoreSlugRouteRoute._addFileChildren(
  StoreSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StoreSlugRouteRoute: StoreSlugRouteRouteWithChildren,
  InvoiceIdRoute: InvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
