-- Advance payment, phase 1: which orders it applies to.
--
--   advance_payment_scope   all (every order, as before), made_to_order (only made-to-order
--                           lines, such as tailoring), delivery (only orders that are delivered)
--                           or made_to_order_or_delivery (a delivered order whole; any other
--                           order only its made-to-order lines)
--
-- orders.advance_scope keeps the scope that applied when the order was placed, next to
-- orders.advance_percent. The storefront reads the setting through brand_public_settings, so
-- the view gains the column at its end (the rest is the live definition, unchanged).
-- Enforcement is in the next migration.

ALTER TABLE public.business_settings
  ADD COLUMN IF NOT EXISTS advance_payment_scope text NOT NULL DEFAULT 'all'
    CHECK (advance_payment_scope IN ('all', 'made_to_order', 'delivery', 'made_to_order_or_delivery'));

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS advance_scope text
    CHECK (advance_scope IS NULL OR advance_scope IN ('all', 'made_to_order', 'delivery', 'made_to_order_or_delivery'));

CREATE OR REPLACE VIEW public.brand_public_settings AS
SELECT bs.brand_id,
    bs.business_name,
    bs.logo_url,
    bs.currency,
    bs.primary_color,
    bs.text_color,
    bs.background_color,
    bs.font_family,
    bs.font_url,
    bs.cod_enabled,
    bs.card_enabled,
    bs.benefit_enabled,
    bs.benefit_qr_url,
    bs.footer_note,
    bs.delivery_fee,
    bs.pickup_enabled,
    bs.delivery_enabled,
    bs.logo_size,
    bs.logo_align,
    bs.header_bg,
    bs.header_fg,
    bs.footer_bg,
    bs.footer_fg,
    bs.heading_color,
    bs.link_color,
    bs.btn_primary_bg,
    bs.btn_primary_fg,
    bs.btn_secondary_bg,
    bs.btn_secondary_fg,
    bs.btn_checkout_bg,
    bs.btn_checkout_fg,
    bs.pages,
    bs.whatsapp_enabled,
    bs.whatsapp_number,
    bs.socials,
    bs.favicon_url,
    bs.show_header_name,
    bs.show_hero_title,
    bs.show_hero_about,
    bs.show_footer_name,
    bs.storefront_font_en,
    bs.storefront_font_ar,
    bs.hero_title_size,
    bs.hero_title_color,
    bs.hero_title_align,
    bs.storefront_font_en_url,
    bs.storefront_font_ar_url,
    bs.hero_title_en,
    bs.hero_title_ar,
    bs.storefront_accent_color,
    bs.storefront_background_color,
    bs.storefront_text_color,
    bs.digital_delivery_enabled,
    bs.menu_bg,
    bs.menu_fg,
    bs.menu_title_en,
    bs.menu_title_ar,
    bs.menu_show_home,
    bs.menu_show_account,
    bs.menu_show_orders,
    bs.menu_show_pages,
    bs.home_promo_cards,
    bs.show_new_arrivals,
    bs.show_best_sellers,
    bs.new_arrivals_title_en,
    bs.new_arrivals_title_ar,
    bs.best_sellers_title_en,
    bs.best_sellers_title_ar,
    bs.announcement_enabled,
    bs.announcement_text_en,
    bs.announcement_text_ar,
    bs.announcement_bg,
    bs.announcement_fg,
    bs.announcement_bold,
    bs.announcement_italic,
    bs.announcement_dismissible,
    bs.announcement_scope,
    bs.announcement_audience,
    bs.global_sale_badges_enabled,
    bs.cart_drawer_checkout_bg,
    bs.cart_drawer_checkout_fg,
    bs.vat_inclusive,
    bs.shipping_zones,
    bs.storefront_loader_text_en,
    bs.storefront_loader_text_ar,
    bs.storefront_radius,
    bs.header_glass,
    bs.badge_accent,
    bs.secondary_banner_parallax_enabled,
    bs.secondary_banner_parallax_mobile_enabled,
    bs.secondary_banner_parallax_breakpoint,
    bs.trending_banner_background_url,
    bs.category_banner_background_url,
    bs.homepage_editorial_sections,
    bs.storefront_typography,
    bs.product_title_color,
    bs.price_color,
    bs.footer_logo_size,
    bs.trust_badges,
    bs.storefront_mode,
    bs.catalog_show_prices,
    bs.catalog_inquiry_message_en,
    bs.catalog_inquiry_message_ar,
    bs.store_vertical,
    bs.store_modules,
    bs.fit_profiles,
    bs.delivery_estimate_enabled,
    bs.delivery_estimate_ar,
    bs.delivery_estimate_en,
    bs.brand_palette,
    bs.invoice_inherit_brand_color,
    bs.invoice_inherit_brand_font,
    bs.storefront_design_version,
    bs.trust_bar_enabled,
    bs.trust_bar_position,
    bs.hero_overlay_strength,
    bs.hero_title_color_v2,
    bs.product_card_hover_image,
    bs.product_card_color_dots,
    bs.product_card_quick_add,
    bs.new_badge_days,
    bs.footer_layout,
    bs.footer_show_payment_methods,
    bs.newsletter_enabled,
    bs.newsletter_title_ar,
    bs.newsletter_title_en,
    bs.brand_story_enabled,
    bs.brand_story_image_url,
    bs.category_filters_enabled,
    bs.pdp_layout,
    bs.pdp_image_zoom,
    bs.social_proof_enabled,
    bs.recently_viewed_enabled,
    bs.motion_enabled,
    bs.quick_view_enabled,
    bs.back_in_stock_enabled,
    bs.fabric_care_ar,
    bs.fabric_care_en,
    bs.shipping_returns_ar,
    bs.shipping_returns_en,
    bs.business_hours_ar,
    bs.business_hours_en,
    bs.bundle_discount_percent,
    bs.hero_layout,
    bs.hero_height_desktop,
    bs.hero_aspect_mobile,
    bs.hero_show_arrows,
    bs.pdp_gallery_aspect_ratio,
    bs.hero_video_fit,
    bs.advance_payment_enabled,
    bs.advance_payment_percent,
    bs.advance_payment_scope
   FROM business_settings bs
     JOIN brands b ON b.id = bs.brand_id
  WHERE b.is_active = true;

GRANT SELECT ON public.brand_public_settings TO anon, authenticated, service_role;
