// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

export function getEnvVariable(name: string): string | undefined {
  const viteName = name.startsWith("VITE_") ? name : `VITE_${name}`;
  const unprefixed = name.startsWith("VITE_") ? name.slice(5) : name;

  // 1. Try process.env
  if (typeof process !== "undefined") {
    if (process.env?.[name]) return process.env[name];
    if (process.env?.[viteName]) return process.env[viteName];
    if (process.env?.[unprefixed]) return process.env[unprefixed];
  }

  // 2. Try import.meta.env (Vite build-time injection)
  try {
    const metaEnv = (import.meta as any).env;
    if (metaEnv?.[name]) return metaEnv[name];
    if (metaEnv?.[viteName]) return metaEnv[viteName];
    if (metaEnv?.[unprefixed]) return metaEnv[unprefixed];
  } catch {}

  // 3. Try globalThis fallbacks
  try {
    const g = globalThis as any;
    if (g?.[name]) return g[name];
    if (g?.[viteName]) return g[viteName];
    if (g?.[unprefixed]) return g[unprefixed];
    
    if (g?.process?.env?.[name]) return g.process.env[name];
    if (g?.process?.env?.[viteName]) return g.process.env[viteName];
    if (g?.process?.env?.[unprefixed]) return g.process.env[unprefixed];
  } catch {}

  return undefined;
}

export async function getEnvVariableAsync(name: string): Promise<string | undefined> {
  const viteName = name.startsWith("VITE_") ? name : `VITE_${name}`;
  const unprefixed = name.startsWith("VITE_") ? name.slice(5) : name;

  // 1. Try Cloudflare request context (runtime environment variables)
  if (typeof window === "undefined") {
    try {
      const vinxiHttp = "vinxi/http";
      const { getEvent } = await import(vinxiHttp);
      const event = getEvent();
      const env = event?.context?.cloudflare?.env || (event?.context as any)?.env;
      if (env?.[name]) return env[name];
      if (env?.[viteName]) return env[viteName];
      if (env?.[unprefixed]) return env[unprefixed];
    } catch {}
  }

  // 2. Fall back to standard synchronous checks
  return getEnvVariable(name);
}



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    let SUPABASE_URL = (await getEnvVariableAsync('SUPABASE_URL')) || (await getEnvVariableAsync('VITE_SUPABASE_URL'));
    if (SUPABASE_URL && !SUPABASE_URL.startsWith('http://') && !SUPABASE_URL.startsWith('https://')) {
      SUPABASE_URL = `https://${SUPABASE_URL}`;
    }
    const SUPABASE_PUBLISHABLE_KEY = (await getEnvVariableAsync('SUPABASE_PUBLISHABLE_KEY')) || (await getEnvVariableAsync('VITE_SUPABASE_ANON_KEY')) || (await getEnvVariableAsync('VITE_SUPABASE_PUBLISHABLE_KEY'));

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Please add them to your hosting provider settings.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
