// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

export function getEnvVariable(name: string): string | undefined {
  const viteName = name.startsWith("VITE_") ? name : `VITE_${name}`;
  const unprefixed = name.startsWith("VITE_") ? name.slice(5) : name;

  // 1. Try real live runtime process.env (bypassing Vite's compile-time static rewriting)
  try {
    const g = globalThis as any;
    const liveEnv = g["process"]?.["env"];
    if (liveEnv) {
      if (liveEnv[name]) return liveEnv[name];
      if (liveEnv[viteName]) return liveEnv[viteName];
      if (liveEnv[unprefixed]) return liveEnv[unprefixed];
    }
  } catch {}

  // 2. Try import.meta.env (Vite build-time injection)
  try {
    const metaEnv = (import.meta as any).env;
    if (metaEnv?.[name]) return metaEnv[name];
    if (metaEnv?.[viteName]) return metaEnv[viteName];
    if (metaEnv?.[unprefixed]) return metaEnv[unprefixed];
  } catch {}

  // 3. Fallback to standard process.env (which Vite rewrites statically at build time)
  try {
    if (process.env?.[name]) return process.env[name];
    if (process.env?.[viteName]) return process.env[viteName];
    if (process.env?.[unprefixed]) return process.env[unprefixed];
  } catch {}

  // 4. Try globalThis fallbacks
  try {
    const g = globalThis as any;
    if (g?.[name]) return g[name];
    if (g?.[viteName]) return g[viteName];
    if (g?.[unprefixed]) return g[unprefixed];
  } catch {}

  return undefined;
}

export async function getEnvVariableAsync(name: string): Promise<string | undefined> {
  const viteName = name.startsWith("VITE_") ? name : `VITE_${name}`;
  const unprefixed = name.startsWith("VITE_") ? name.slice(5) : name;

  // 1. Try Cloudflare request context (runtime environment variables)
  if (typeof window === "undefined") {
    try {
      const vinxiHttp = "vinxi/http";
      const { getEvent } = await import(vinxiHttp);
      const event = getEvent();
      const env = event?.context?.cloudflare?.env || 
                  (event?.context as any)?.env || 
                  event?.context?.cloudflare || 
                  (event?.context as any)?.cloudflare?.env;
      if (env) {
        if (env[name]) return env[name];
        if (env[viteName]) return env[viteName];
        if (env[unprefixed]) return env[unprefixed];
      }
    } catch (e) {
      if (name === "GEMINI_API_KEY") {
        console.error(`[Env Debug] Error reading Cloudflare context:`, e);
      }
    }
  }

  // 2. Fall back to standard synchronous checks
  return getEnvVariable(name);
}

export async function getEnvDiagnostics(): Promise<{ keys: string[]; hasProcess: boolean; hasCloudflare: boolean }> {
  const keys = new Set<string>();
  let hasProcess = false;
  let hasCloudflare = false;

  // 1. Live process.env (bracket notation to bypass Vite compilation)
  try {
    const g = globalThis as any;
    const liveEnv = g["process"]?.["env"];
    if (liveEnv) {
      hasProcess = true;
      Object.keys(liveEnv).forEach(k => keys.add(k));
    }
  } catch {}

  // 2. Cloudflare request context
  if (typeof window === "undefined") {
    try {
      const vinxiHttp = "vinxi/http";
      const { getEvent } = await import(vinxiHttp);
      const event = getEvent();
      const env = event?.context?.cloudflare?.env || 
                  (event?.context as any)?.env || 
                  event?.context?.cloudflare || 
                  (event?.context as any)?.cloudflare?.env;
      if (env) {
        hasCloudflare = true;
        Object.keys(env).forEach(k => keys.add(k));
      }
    } catch {}
  }

  // 3. Static process.env (Vite compilation will rewrite)
  try {
    if (process.env) {
      Object.keys(process.env).forEach(k => keys.add(k));
    }
  } catch {}

  // 4. import.meta.env
  try {
    const metaEnv = (import.meta as any).env;
    if (metaEnv) {
      Object.keys(metaEnv).forEach(k => keys.add(k));
    }
  } catch {}

  // Filter out sensitive-looking keys for safety, but keep key schemas
  const filteredKeys = Array.from(keys).map(k => {
    if (k.length > 30) return `${k.substring(0, 5)}... (len: ${k.length})`;
    return k;
  });

  return {
    keys: filteredKeys,
    hasProcess,
    hasCloudflare
  };
}



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    let SUPABASE_URL = (await getEnvVariableAsync('SUPABASE_URL')) || (await getEnvVariableAsync('VITE_SUPABASE_URL'));
    if (SUPABASE_URL && !SUPABASE_URL.startsWith('http://') && !SUPABASE_URL.startsWith('https://')) {
      SUPABASE_URL = `https://${SUPABASE_URL}`;
    }
    const SUPABASE_PUBLISHABLE_KEY = (await getEnvVariableAsync('SUPABASE_PUBLISHABLE_KEY')) || (await getEnvVariableAsync('VITE_SUPABASE_ANON_KEY')) || (await getEnvVariableAsync('VITE_SUPABASE_PUBLISHABLE_KEY'));

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Please add them to your hosting provider settings.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);

/**
 * Retrieves Gemini credentials (API key and optional custom model) from
 * either the system environment variables or the database-backed integration settings.
 * This completely bypasses hosting-provider environmental issues.
 */
export async function getGeminiCredentials(
  supabase: any,
  userId: string
): Promise<{ apiKey: string | undefined; model: string | undefined }> {
  let apiKey = await getEnvVariableAsync("GEMINI_API_KEY");
  let model: string | undefined = undefined;

  try {
    const { data: profile } = await supabase
      .from("profiles")
      .select("brand_id")
      .eq("id", userId)
      .single();
    
    if (profile?.brand_id) {
      const { data: integration } = await supabase
        .from("integration_credentials")
        .select("api_key, base_url")
        .eq("brand_id", profile.brand_id)
        .eq("provider", "gemini")
        .eq("is_active", true)
        .maybeSingle();
      
      if (integration?.api_key) {
        apiKey = integration.api_key;
        if (integration.base_url) {
          model = integration.base_url.trim();
        }
      }
    }
  } catch (e) {
    console.error("[getGeminiCredentials] Error querying database for custom Gemini integration:", e);
  }

  return { apiKey, model };
}

